In [5]:
import pandas as pd

In [6]:
df=pd.read_csv(r"D:\Amazon ML\dataset\student_resource\dataset\train\train_source3.tsv",sep="\t")

In [7]:
df.shape

(5285603, 4)

In [8]:
df.head

<bound method NDFrame.head of             entity_id                                business_name  \
0        S3-202863386                           wilfordhancock.com
1        S3-859268022  International South Consultants Private Ltd
2         S3-22467283                  LLC Moncada Léarning Center
3        S3-671162755                               Moyna's Coffee
4        S3-960981775                 Pvt. EFS Print Ventures Ltd.
...               ...                                          ...
5285598  S3-549653960                                Vip Solutions
5285599   S3-45212707                           Cornerstone Nippon
5285600  S3-257390113                              Legacy Piedmont
5285601   S3-97881155                         Pranava Meribl Trust
5285602  S3-864344230             The Trusted Defense Products Inc

                                          business_address country
0                              Mack Rd, Haltom City, Texas      US
1                                                      NaN   India
2                          5780 Fawn Ct, Fort Worth, Texas      US
3             1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4        Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India
...                                                    ...     ...
5285598                                                NaN   India
5285599               Paula Drive, Arkansas, N Little Rock      US
5285600                       Portland, Maine, Forest Park      US
5285601  235, 13Th Cross Road, Hoyasala Ngr 2D Stage, B...   India
5285602                                                NaN      US

[5285603 rows x 4 columns]>

In [9]:
df.info

<bound method DataFrame.info of             entity_id                                business_name  \
0        S3-202863386                           wilfordhancock.com
1        S3-859268022  International South Consultants Private Ltd
2         S3-22467283                  LLC Moncada Léarning Center
3        S3-671162755                               Moyna's Coffee
4        S3-960981775                 Pvt. EFS Print Ventures Ltd.
...               ...                                          ...
5285598  S3-549653960                                Vip Solutions
5285599   S3-45212707                           Cornerstone Nippon
5285600  S3-257390113                              Legacy Piedmont
5285601   S3-97881155                         Pranava Meribl Trust
5285602  S3-864344230             The Trusted Defense Products Inc

                                          business_address country
0                              Mack Rd, Haltom City, Texas      US
1                                                      NaN   India
2                          5780 Fawn Ct, Fort Worth, Texas      US
3             1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4        Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India
...                                                    ...     ...
5285598                                                NaN   India
5285599               Paula Drive, Arkansas, N Little Rock      US
5285600                       Portland, Maine, Forest Park      US
5285601  235, 13Th Cross Road, Hoyasala Ngr 2D Stage, B...   India
5285602                                                NaN      US

[5285603 rows x 4 columns]>

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB

In [11]:
df.isnull().sum()

entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

In [12]:
df.head

<bound method NDFrame.head of             entity_id                                business_name  \
0        S3-202863386                           wilfordhancock.com
1        S3-859268022  International South Consultants Private Ltd
2         S3-22467283                  LLC Moncada Léarning Center
3        S3-671162755                               Moyna's Coffee
4        S3-960981775                 Pvt. EFS Print Ventures Ltd.
...               ...                                          ...
5285598  S3-549653960                                Vip Solutions
5285599   S3-45212707                           Cornerstone Nippon
5285600  S3-257390113                              Legacy Piedmont
5285601   S3-97881155                         Pranava Meribl Trust
5285602  S3-864344230             The Trusted Defense Products Inc

                                          business_address country
0                              Mack Rd, Haltom City, Texas      US
1                                                      NaN   India
2                          5780 Fawn Ct, Fort Worth, Texas      US
3             1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4        Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India
...                                                    ...     ...
5285598                                                NaN   India
5285599               Paula Drive, Arkansas, N Little Rock      US
5285600                       Portland, Maine, Forest Park      US
5285601  235, 13Th Cross Road, Hoyasala Ngr 2D Stage, B...   India
5285602                                                NaN      US

[5285603 rows x 4 columns]>

In [13]:
df.head(5)

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [14]:
df.head()

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [15]:
df.shape

(5285603, 4)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB

In [17]:
df.columns

Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='str')

In [18]:
for col in df.select_dtypes(include="str").columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(20))

--- entity_id ---
entity_id
S3-202863386    1
S3-859268022    1
S3-22467283     1
S3-671162755    1
S3-960981775    1
S3-578159284    1
S3-121412624    1
S3-249416830    1
S3-107644605    1
S3-160217003    1
S3-504183980    1
S3-53737228     1
S3-16693061     1
S3-331103166    1
S3-45067784     1
S3-118652570    1
S3-90100170     1
S3-476778426    1
S3-128062172    1
S3-171901473    1
Name: count, dtype: int64

--- business_name ---
business_name
Primary Care           421
Physical Therapy       399
Pediatric Dental       393
Womens Health          379
Urgent Care            377
Pediatric Dentistry    361
Behavioral Health      330
Pediatric              321
Internal Medicine      319
The Dent               254
Straight Edge          252
Foot & Ankle           240
Ear Nose & Throat      238
earnosethroat.com      238
Main Street            231
Back Alley             222
SC                     197
Apex                   192
Vision                 185
SI                     180
Name: count, dtype: int64

--- business_address ---
business_address
NaN                             175916
Ground Floor, Bangalore, KA         29
Floor, Mumbai, MH                   26
18, Kolkata, Howrah, WB             26
303, Mumbai, MH                     25
12, Ahmedabad, GJ                   23
101, Mumbai, Mumbai City, MH        23
4, Mumbai, MH                       23
Floor, Bangalore, KA                22
7, Kolkata, Howrah, WB              21
5, Ahmedabad, GJ                    21
601, Mumbai, MH                     21
301, Mumbai, Mumbai City, MH        21
3, Ahmedabad, GJ                    21
1, Kolkata, Howrah, WB              21
2, Mumbai, MH                       20
10, Kolkata, Howrah, WB             20
2, Mumbai, Mumbai City, MH          20
3, Kolkata, Howrah, WB              20
4, Kolkata, Howrah, WB              20
Name: count, dtype: int64

--- country ---
country
US       3170056
India    2115547
Name: count, dtype: int64

In [19]:
df[df["business_name"].str.contains(
    r"\b(pvt|private|ltd|limited|corp|corporation)\b",
    case=False,
    na=False
)]["business_name"].value_counts().head(100)

C:\Users\madha\AppData\Local\Temp\ipykernel_5364\3185147793.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df["business_name"].str.contains(

business_name
Mumbai Private Limited Center     51
Shree Private Limited Center      37
Life Private Limited Center       34
Hotel Private Limited Center      34
Gold Private Limited Center       33
                                  ..
One Private Limited Center        20
Arihant Private Limited Center    19
Laxmi Private Limited Center      19
Ss Private Limited Services       19
Bastion Corp                      19
Name: count, Length: 100, dtype: int64

In [20]:
matches = df[df["business_name"].str.contains(
    r"\b(?:pvt|private|ltd|limited|corp|corporation)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 1465088
business_name
Mumbai Private Limited Center     51
Shree Private Limited Center      37
Life Private Limited Center       34
Hotel Private Limited Center      34
Gold Private Limited Center       33
                                  ..
One Private Limited Center        20
Arihant Private Limited Center    19
Laxmi Private Limited Center      19
Ss Private Limited Services       19
Bastion Corp                      19
Name: count, Length: 100, dtype: int64

In [21]:
matches = df[df["business_name"].str.contains(
    r"\b(?:corp|corporation|)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 5285590
business_name
Primary Care         421
Physical Therapy     399
Pediatric Dental     393
Womens Health        379
Urgent Care          377
                    ...
Chiropractic Care    101
Southern             101
Prime                101
New Delhi            101
Aspen                100
Name: count, Length: 100, dtype: int64

In [22]:
matches=df[df["business_name"].str.contains(
    r"\bcorporation|corp\b",
    case=False,
    na=False
)]["business_name"].value_counts().head(100)

In [23]:
matches = df[df["business_name"].str.contains(
    r"\b(?:corp|corporation)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 198023
business_name
Meridian Corp                          21
Solstice Corp                          20
Bastion Corp                           19
Crestline Corp                         18
Lynx Corp                              17
                                       ..
Cardiology Care Associates Corp         9
Obsidian Corp                           9
Raven Corp                              9
Pediatric Dentistry Associates Corp     9
Summit Corporation                      9
Name: count, Length: 100, dtype: int64

In [24]:
matches = df[df["business_name"].str.contains(
    r"\b(?:pvt|private)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 860147
business_name
Mumbai Private Limited Center     51
Shree Private Limited Center      37
Life Private Limited Center       34
Hotel Private Limited Center      34
Gold Private Limited Center       33
                                  ..
My Private Limited Center         19
Shiva Private Limited Center      19
Sai Private Limited Services      19
Chennai Private Limited Center    19
Balaji Private Limited Center     19
Name: count, Length: 100, dtype: int64

In [25]:
matches = df[df["business_name"].str.contains(
    r"\b(?:ltd|limited)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 1101240
business_name
Mumbai Private Limited Center      51
Shree Private Limited Center       37
Life Private Limited Center        34
Hotel Private Limited Center       34
Gold Private Limited Center        33
                                   ..
Ss Private Limited Services        19
Creative Private Limited Center    19
Kolkata Pvt Ltd Center             19
My Private Limited Center          19
Shiva Private Limited Center       19
Name: count, Length: 100, dtype: int64

In [26]:
print("Missing:", df["business_address"].isna().sum())
print("Missing %:", df["business_address"].isna().mean() * 100)

Missing: 175916
Missing %: 3.3282106128666875

In [27]:
print("Empty:", df["business_address"].fillna("").str.strip().eq("").sum())

Empty: 175916

In [28]:
print("Unique addresses:", df["business_address"].nunique())
print("Duplicate rows:", df["business_address"].duplicated().sum())

Unique addresses: 4632764
Duplicate rows: 652838

In [29]:
print("Unique names:", df["business_name"].nunique())
print("Duplicate rows:", df["business_name"].duplicated().sum())

Unique names: 4651608
Duplicate rows: 633994

In [30]:
print(df["business_address"].value_counts(dropna=False).head(50))

business_address
NaN                                                     175916
Ground Floor, Bangalore, KA                                 29
Floor, Mumbai, MH                                           26
18, Kolkata, Howrah, WB                                     26
303, Mumbai, MH                                             25
12, Ahmedabad, GJ                                           23
101, Mumbai, Mumbai City, MH                                23
4, Mumbai, MH                                               23
Floor, Bangalore, KA                                        22
7, Kolkata, Howrah, WB                                      21
5, Ahmedabad, GJ                                            21
601, Mumbai, MH                                             21
301, Mumbai, Mumbai City, MH                                21
3, Ahmedabad, GJ                                            21
1, Kolkata, Howrah, WB                                      21
2, Mumbai, MH                                               20
10, Kolkata, Howrah, WB                                     20
2, Mumbai, Mumbai City, MH                                  20
3, Kolkata, Howrah, WB                                      20
4, Kolkata, Howrah, WB                                      20
2, Kolkata, Howrah, WB                                      20
301, Mumbai, MH                                             19
1, Mumbai, MH                                               19
1, Chennai, TN                                              18
1948. Weaver Forest Way, Morrisville, North Carolina        18
1, Bangalore, KA                                            18
202, Mumbai, MH                                             18
5, Chennai, TN                                              18
Ground Floor, Mumbai, Mumbai City, MH                       18
16, Kolkata, Howrah, WB                                     18
102, Mumbai, Mumbai City, MH                                17
10, Mumbai, Mumbai City, MH                                 17
13, Mumbai, MH                                              17
3401 150, Milan, Indiana                                    17
No.1, Chennai, TN                                           17
101, Indore, MP                                             17
702, Mumbai, MH                                             17
5, Kolkata, Howrah, WB                                      17
301, Ahmedabad, GJ                                          17
101, Mumbai, MH                                             17
6, Mumbai, MH                                               17
1108 1340, Orem, Utah                                       17
8, Kolkata, Howrah, WB                                      17
201, Mumbai, MH                                             17
501, Mumbai, Mumbai City, MH                                17
12, Kolkata, Howrah, WB                                     17
3, Mumbai, MH                                               16
401, Mumbai, Mumbai City, MH                                16
##24233 48, Woodland, Alabama                               16
4, Mumbai, Mumbai City, MH                                  16
Name: count, dtype: int64

In [31]:
for col in df.select_dtypes(include="str").columns:
    count = (
        df[col].notna() &
        (df[col] != df[col].str.strip())
    ).sum()

    print(col, "→", count)

entity_id → 0
business_name → 0
business_address → 0
country → 0

In [32]:
for col in df.select_dtypes(include="str").columns:
    original = df[col].dropna()
    normalized = original.str.strip().str.lower()

    print(
        col,
        "→ original unique:", original.nunique(),
        "| lowercase unique:", normalized.nunique()
    )

entity_id → original unique: 5285603 | lowercase unique: 5285603
business_name → original unique: 4651608 | lowercase unique: 4579083
business_address → original unique: 4632764 | lowercase unique: 4632184
country → original unique: 2 | lowercase unique: 2

In [33]:
name_norm = (
    df["business_name"]
    .astype("string")
    .str.strip()
    .str.lower()
)

groups = (
    pd.DataFrame({
        "original": df["business_name"],
        "normalized": name_norm
    })
    .dropna()
    .groupby("normalized")["original"]
    .nunique()
    .sort_values(ascending=False)
)

print(groups.head(30))

normalized
department of environmental protection    5
division of motor vehicles                5
division of housing                       5
ear nose & throat care associates llc     5
frontier institute of technology          5
department of education llc               5
foot & ankle physicians llc               5
eye clinic llc                            5
cardiology care llc                       5
department of finance                     5
commission on health                      5
commission on sanitation                  5
division of public works                  5
ear nose & throat associates llc          5
cardiology care associates llc            5
commission on veterans affairs            5
division of health                        5
eye partners llc                          5
ear nose & throat care llc                5
bureau of finance                         5
ear nose & throat physicians llc          5
department of housing                     5
ear nose & throat partners llc            5
foot & ankle partners llc                 5
foot & ankle clinic llc                   5
behavioral health care associates llc     5
bureau of public works                    5
bureau of transportation llc              5
division of parks and recreation          5
board of sanitation                       5
Name: original, dtype: int64

In [34]:
print(
    df.loc[
        name_norm == "department of environmental protection",
        "business_name"
    ].value_counts()
)

business_name
Department of Environmental Protection    3
DEPARTMENT OF ENVIRONMENTAL PROTECTION    1
Department Of Environmental Protection    1
Department OF Environmental Protection    1
department of environmental protection    1
Name: count, dtype: int64

In [35]:
name_norm = (
    df["business_name"]
    .astype("string")
    .str.strip()
    .str.lower()
)

mask = (
    df["business_name"].notna()
    & (df["business_name"] != name_norm)
)

print("Rows affected:", mask.sum())
print(df.loc[mask, ["business_name"]].drop_duplicates().head(100).to_string(index=False))

Rows affected: 4711315
                              business_name
International South Consultants Private Ltd
                LLC Moncada Léarning Center
                             Moyna's Coffee
               Pvt. EFS Print Ventures Ltd.
             LLC Hernandez Colonial Redwood
              Classic Equity Partners Group
             Ectolumdrex dba X+ Madison Inc
                    Animal Hanisch Hospirlg
                              Gomez Optimal
           The Rapid  Learning Alliance LLC
                 Indian Care Public Limited
                                      Béque
        அரிஹந்த் Foundation Private Limited
                        Wildlife Guild  LLC
                         Cinder Charlton-PC
                             ZRO Trinity Co
          Bajaj Foundation  Private Limited
                          Estell's Creative
                         Center 5uperior Co
                           Palace Vidyalaya
                             Global Applied
               Integrated  Business Systems
Cardiology Heartland Cáre Associates #98825
                  Sai  Surgical (India) Ltd
MW Management Private  Limited - 2067865001
                       FERRERO FERRERO DUKE
          Chinglepet Private Limited Center
                     Modern Center Brothers
                     Navkar Sons Ltd Center
                      Compher's Auto  Glass
                 గుజరాత్ Logistics లిమిటెడ్
             Stellar + Brothers Private Ltd
                 Ear N0se & Throat Regional
                 Best Software Innovations,
      Capital-Snow Capital-Snow Corporation
                               SAV Holdings
              Mr Om-Consultants Corporation
                             Cozy Shop Bike
                           LLC Safe Newbury
                Shree Sgpeciarity Pvt. Ltd.
                           Little Ice Cirhm
                                Hmgreen.Com
                              TV Tower Inc.
     Orthopedic Specialists Of Fort Wht LLC
                      Raj Black [Marketing]
                    M/s Jd Pvt Ltd Services
                         Davis  Acquisition
                           Mitchell Acbdeyg
                     Secure Secure Cárolina
                            Montica LLC Vii
                            Clear [Payroll]
                    Basalt Forefront L.L.C.
              Royal Mémorial Trust Holdings
                   Snell Cmpleee Glass Corp
  The Consultants Karnataka Cotex (Limited)
                       Honey Balzer, MD Ltd
                     Harbor Foundation  III
           Physical Group Precision Therapy
          Quonex d/b/a M D Herrera Offshore
         Ken Hospitalities (India)  Limited
                        Odetta Robinson Oak
   Bennett & Mofcno Canary of Liverpoo1 Ltd
          Private Shivam Projects [Limited]
        Chavarin Property óf Queensbury LLC
                             #Apexphotonics
        Perine Heritage Family Practice LLC
   Lopez Continental  Arcelormittal Greater
         Cultural Coalition Ltd Association
                   Jsg Enterprises (Center)
    Mr Chalakudy-+ Partners Private Limited
                       Leahy Silver  Acp LP
                            Edgar Space Inc
         Private Unique Enterprises Limited
                                  NV Pharma
         Karo1's Capital Restaurant  Clginc
         Umbraonyx dba Filson Apex Chemical
                Hyacinthe L. Cheung D.C. PC
                Piedmont Liberty Octave Llc
        Digital Hospitality Private Limited
                      Bonnettresilience.Com
  Solutions Accuracy Healthcare-Private Ltd
                     Tu Ventures  Pvt (Ltd)
                 Innovative Cargo  Concepts
             Heartland Optimal Médicine LLC
              Sachet Agro Infratech Limited
                                     Dental
                                 Monarch Co
           Mclaughlin, Blanco  & Walker Ltd
    Finance Divya Balaji  Private [Limited]
               (Ltd) Producer Aim Solutions
                   -- Maryl-Khalil Old Corp
                                    Wexnyla
                               Werner Aegon
       Insightful & Sons Industries Limited
           Baptist Ássociation Northside LP
    Morales, Godina & Pánkow Associates LLC
                     Germana Ott Slaect-Oyj
                           Lee Illumination
            Shaffer Xcblla LLC - 7934786696
                  Akridge Family [Practice]

In [36]:
print(df.shape)
print(df["business_name"].head(10))

(5285603, 4)
0                             wilfordhancock.com
1    International South Consultants Private Ltd
2                    LLC Moncada Léarning Center
3                                 Moyna's Coffee
4                   Pvt. EFS Print Ventures Ltd.
5                 LLC Hernandez Colonial Redwood
6                  Classic Equity Partners Group
7                 Ectolumdrex dba X+ Madison Inc
8                        Animal Hanisch Hospirlg
9                                  Gomez Optimal
Name: business_name, dtype: str

In [37]:
print(df.shape)
print(df.columns.tolist())
print(df.info())

(5285603, 4)
['entity_id', 'business_name', 'business_address', 'country']
<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB
None

In [38]:
print(df.isna().sum())

entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

In [39]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate entity IDs:", df["entity_id"].duplicated().sum())

Duplicate rows: 0
Duplicate entity IDs: 0

In [40]:
print(df["business_address"].dropna().sample(100, random_state=42).to_string(index=False))

                 781 Skyview Road, Salem, Virginia
Near Raunak Marriage Hall, Nalapar Afridiyan, R...
      123rd Ave, LKAE Stevens Township, Washington
447 Tranquila Drive, Camarillo Township, Califo...
              Morganton, 1254 Burkemont Avenue, NC
Keralam, Thirunakkra, Kottayam, Xii/74, First F...
Aligarh, #33 Panch Visa Jattari, Jatari, उत्तर ...
Gunjur, Door No 9245, Bangalore, KA, Gunjur Mai...
3490 Richpod-Rockfield Rd, Unit 6, Bowling Gree...
                   Sagecroft Drive, Houston, Texas
Hyderabad, Block-d, Maruthi Elite Gated Communi...
     2424 Heartstone Court, Clarksville, Tennessee
                230-234 3rd St, Ohio, Williamsburg
          Plot 300 244, Tilak Nagar, New Delhi, DL
708, Palms One, Royal Palms Estates Aarey Milk ...
46 Robert Ford Road, # 4, Watertown, Massachusetts
         916 Purple Moor Pass, Leanedr CITY, Texas
         16720 North Road, Martha Lake, Washington
           DL, Delhi, Wz-51a, First Floor Toda Pur
Hayatnagar, 3-53, Saroornagar, Sri Venkateswara...
                 508 8st St, Bucyrus, North Dakota
   #374 9-16-26, Vishakhapatnam, Visakhapatnam, AP
              Talwakars, Mahim, Mumbai, महाराष्ट्र
3031- Research Dr, PMB 5911, State College, Pen...
             380B Laneda Avenue, Manzanita, Oregon
12 Entire Basement And Ground Floor, New Delhi, DL
*Lien 1 Shop No 8 Tirupat, Complex Railway Road...
            Houston, Texas, #1614 Southmore Avenue
        1305 185th Dr, Goodyear, PMB 4324, Arizona
              5 West Street, <NULL>, Dellroy, Ohio
                                    B-12, Kota, RJ
2112-2114 Eighth St, Washington, District of Co...
                 434 Highland Court, Owensboro, KY
 126- Stewart Avenue, Moooresville, North Carolina
           #4515 Ghost Rider Way, Rimrock, Arizona
2580 Old A J Hwy, null, Strawberry Plains, Tenn...
Dheeraj Heritage, Comm Complex, Thane, Bg 26, M...
    Gateway Ln, N/A, Winston-Salem, North Carolina
               559  Ekman Drive, Batavia, Illinois
         Alaska, Fairbanks CITY, 452 Rhonda Street
            3405 25th Street, Tuscalooosa, Alabama
           B-60, Gautam Buddha Nagar, उत्तर प्रदेश
No. 3 Sfno 592/13, Avalurpettai Salai Kilpennat...
                Shop No.-##12, South Delhi, दिल्ली
           104 Mechunk Creek Drive, Troy, Virginia
              3- Maye St, Binghamton CDP, New York
              430 Devonshire Drive, Prosper, Texas
                         Lester Road, Medina, Ohio
                       No. 17, Madras, Chennai, TN
           1401 Ashland Ave, Saint Paul, Minnesota
    Eugene, 031547 Coburg Bottom Loop Road, Oregon
      #177 N Lacarpe Circle, Houma CITY, Louisiana
          2347 Blaine Drive, Chevy Chase, Maryland
   3034 Gardenia Lane, Floor 1, Oympia, Washington
      Mona Ln, Building 24, West Jordan City, Utah
No 2682 Nayabad, 1St Floor Fl-01, Kolkata, Howr...
             4304 Plantation Rd, Roanoke, Virginia
20, Opp. Balaji Furniture House Rajeev Colony, ...
   1250 Blue Hills Avenue, Bloomfield, Connecticut
              2944 1/2 8th St, Minot, North Dakota
                        A-00270, New Delhi, दिल्ली
Plot No.533, Dattasudha, Sindh Housing Society ...
                 1110 Chestnut St, Casper, Wyoming
1822 South Drive, Jacksonville CITY, North Caro...
157 Amcakassin Ter, Unit Apartment 2, Yonkers, ...
                  144 Lemcke Rd, Beavercreek, Ohio
                 07221 Heron Ln, Texas City, Texas
Flat No. A-7, New Shivsagar Housing Society, Ne...
#2050 (Old No. 29), 15Th Cross, Near Gundanjane...
5Thcross, 3Rdmain2Ndstage, Vijaynagar, KA, 2205...
           3380 Lakewood Dr, Harrionburg, Virginia
131, E-8, Basant Kunj, 12 No. Stop, Arera Colon...
             ##270 Munn Rd, Southbury, Connecticut
         7502 Monarch Mills Way, Coumbia, Maryland
              9236 158, Stokesdale, North Carolina
1114 Twenty-Ninth St, Winston-Salem, North Caro...
        Texas, Autsin CITY, 7600 Covered Bridge Dr
Thane, Vidarbha Mahesh Chs, C Bhavan Bldg, S N ...
21/1A/3, Darga Road, Jindal Towers Block-b, 5Th...
           ##7963 Throop Street, Chicago, Illinois
Gujranwala Town, DL, New Delhi, G-8 Kirpal Bhaw...
48 Scuppernong Lane, Southern Shores, North Car...
312 Millbrook Road, # 233, Raleigh, North Carolina
     158 6 B7near Main Bus Stand Kothrud, Pune, MH
    Apache Junction, Arizona, 1006 Santa Cruz Lane
800 Napa Valley Drive, Unit Apt 197, Little Roc...
            10866 69th Ave, Maple Grove, Minnesota
No 004, First Floor Sai Ram Paradise, Sujatha N...
                         A/2705, Thane, महाराष्ट्र
                 35-39 Russell Avenue, Niles, Ohio
                   NM, Carlsbad, 413 Laredo Street
            0108 Lakeside Drive, Smyrna, Tennessee
    118- Princeton Street, Manchester, Connecticut
               Cambridge Rd, Woburn, Massachusetts
   8661 Hotchkiss Street, Sterling Ranch, Colorado
                  Cleveland, Ohio, 573 124th Saint
           4041 Hillsdale Cir, Tuscaloosa, Alabama
          16 Meadows Avenue, Canton, Massachusetts
               30 Juno Drive, Wentzville, Missouri
Santi Niketan6 Race Course 6 Race Course, Coimb...

In [41]:
address_space = (
    df["business_address"].notna()
    & (df["business_address"] != df["business_address"].str.strip())
)

print("Addresses with leading/trailing spaces:", address_space.sum())

Addresses with leading/trailing spaces: 0

In [42]:
address_norm = (
    df["business_address"]
    .astype("string")
    .str.strip()
)

print(
    "Addresses affected by leading/trailing spaces:",
    (df["business_address"].notna() &
     (df["business_address"] != address_norm)).sum()
)

Addresses affected by leading/trailing spaces: 0

In [43]:
original_unique = df["business_address"].dropna().nunique()
normalized_unique = address_norm.dropna().nunique()

print("Original unique addresses:", original_unique)
print("After strip unique:", normalized_unique)

Original unique addresses: 4632764
After strip unique: 4632764

In [44]:
print(
    df["business_address"]
    .value_counts(dropna=False)
    .head(50)
)

business_address
NaN                                                     175916
Ground Floor, Bangalore, KA                                 29
Floor, Mumbai, MH                                           26
18, Kolkata, Howrah, WB                                     26
303, Mumbai, MH                                             25
12, Ahmedabad, GJ                                           23
101, Mumbai, Mumbai City, MH                                23
4, Mumbai, MH                                               23
Floor, Bangalore, KA                                        22
7, Kolkata, Howrah, WB                                      21
5, Ahmedabad, GJ                                            21
601, Mumbai, MH                                             21
301, Mumbai, Mumbai City, MH                                21
3, Ahmedabad, GJ                                            21
1, Kolkata, Howrah, WB                                      21
2, Mumbai, MH                                               20
10, Kolkata, Howrah, WB                                     20
2, Mumbai, Mumbai City, MH                                  20
3, Kolkata, Howrah, WB                                      20
4, Kolkata, Howrah, WB                                      20
2, Kolkata, Howrah, WB                                      20
301, Mumbai, MH                                             19
1, Mumbai, MH                                               19
1, Chennai, TN                                              18
1948. Weaver Forest Way, Morrisville, North Carolina        18
1, Bangalore, KA                                            18
202, Mumbai, MH                                             18
5, Chennai, TN                                              18
Ground Floor, Mumbai, Mumbai City, MH                       18
16, Kolkata, Howrah, WB                                     18
102, Mumbai, Mumbai City, MH                                17
10, Mumbai, Mumbai City, MH                                 17
13, Mumbai, MH                                              17
3401 150, Milan, Indiana                                    17
No.1, Chennai, TN                                           17
101, Indore, MP                                             17
702, Mumbai, MH                                             17
5, Kolkata, Howrah, WB                                      17
301, Ahmedabad, GJ                                          17
101, Mumbai, MH                                             17
6, Mumbai, MH                                               17
1108 1340, Orem, Utah                                       17
8, Kolkata, Howrah, WB                                      17
201, Mumbai, MH                                             17
501, Mumbai, Mumbai City, MH                                17
12, Kolkata, Howrah, WB                                     17
3, Mumbai, MH                                               16
401, Mumbai, Mumbai City, MH                                16
##24233 48, Woodland, Alabama                               16
4, Mumbai, Mumbai City, MH                                  16
Name: count, dtype: int64

In [45]:
empty_address = (
    df["business_address"]
    .astype("string")
    .str.strip()
    .eq("")
)

print("Empty addresses:", empty_address.sum())

Empty addresses: 0

In [46]:
print(
    df.loc[
        empty_address,
        "business_address"
    ].value_counts(dropna=False)
)

Series([], Name: count, dtype: int64)

In [47]:
for col in df.select_dtypes(include="str").columns:
    count = (
        df[col].notna() &
        (df[col] != df[col].str.strip())
    ).sum()

    print(f"{col}: {count}")

entity_id: 0
business_name: 0
business_address: 0
country: 0

In [48]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [49]:
address_length = df["business_address"].astype("string").str.len()

print("Mean:", address_length.mean())
print("Median:", address_length.median())
print("Skewness:", address_length.skew())

Mean: 48.32271918025507
Median: 42.0
Skewness: 1.560720077016944

In [50]:
Q1 = address_length.quantile(0.25)
Q3 = address_length.quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)

outliers = (address_length < lower) | (address_length > upper)

print("Outlier count:", outliers.sum())

Q1: 35
Q3: 55
IQR: 20
Lower bound: 5.0
Upper bound: 85.0
Outlier count: 355073

In [51]:
name_length = df["business_name"].astype("string").str.len()

print("Mean:", name_length.mean())
print("Median:", name_length.median())
print("Skewness:", name_length.skew())

Mean: 25.202200889588486
Median: 25.0
Skewness: 0.41363064040643693

In [52]:
Q1 = name_length.quantile(0.25)
Q3 = name_length.quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)

outliers = (name_length < lower) | (name_length > upper)

print("Outlier count:", outliers.sum())

Q1: 18
Q3: 31
IQR: 13
Lower bound: -1.5
Upper bound: 50.5
Outlier count: 50167

In [53]:
df["entity_id"].nunique()

5285603

In [54]:
print(df.shape)
print(df.info())
print(df.isna().sum())
print(df.nunique())

(5285603, 4)
<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB
None
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64
entity_id           5285603
business_name       4651608
business_address    4632764
country                   2
dtype: int64

In [55]:
for col in df.columns:
    print(f"\n===== {col} =====")
    print("Unique:", df[col].nunique())
    print("Missing:", df[col].isna().sum())
    print(df[col].astype(str).str.len().describe())

===== entity_id =====
Unique: 5285603
Missing: 0
count    5.285603e+06
mean     1.188873e+01
std      3.512252e-01
min      5.000000e+00
25%      1.200000e+01
50%      1.200000e+01
75%      1.200000e+01
max      1.200000e+01
Name: entity_id, dtype: float64

===== business_name =====
Unique: 4651608
Missing: 13
count    5.285590e+06
mean     2.520220e+01
std      9.493565e+00
min      2.000000e+00
25%      1.800000e+01
50%      2.500000e+01
75%      3.100000e+01
max      1.230000e+02
Name: business_name, dtype: float64

===== business_address =====
Unique: 4632764
Missing: 175916
count    5.109687e+06
mean     4.832272e+01
std      2.017758e+01
min      2.000000e+00
25%      3.500000e+01
50%      4.200000e+01
75%      5.500000e+01
max      2.400000e+02
Name: business_address, dtype: float64

===== country =====
Unique: 2
Missing: 0
count    5.285603e+06
mean     3.200741e+00
std      1.469845e+00
min      2.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      5.000000e+00
max      5.000000e+00
Name: country, dtype: float64

In [56]:
print(df["country"].value_counts(dropna=False))

country
US       3170056
India    2115547
Name: count, dtype: int64

In [57]:
name_counts = df["business_name"].value_counts()

print(name_counts.head(30))

business_name
Primary Care           421
Physical Therapy       399
Pediatric Dental       393
Womens Health          379
Urgent Care            377
Pediatric Dentistry    361
Behavioral Health      330
Pediatric              321
Internal Medicine      319
The Dent               254
Straight Edge          252
Foot & Ankle           240
Ear Nose & Throat      238
earnosethroat.com      238
Main Street            231
Back Alley             222
SC                     197
Apex                   192
Vision                 185
SI                     180
Cascade                172
Global                 168
Human Rights           168
Division of            168
Summit                 166
Office of              163
Golden                 163
Commission on          162
Autism Assistance      161
SS                     160
Name: count, dtype: int64

In [58]:
patterns = r'private|pvt|limited|ltd|corporation|corp|inc|incorporated|llc|llp'

mask = df["business_name"].str.contains(
    patterns,
    case=False,
    na=False,
    regex=True
)

print(df.loc[mask, "business_name"].value_counts().head(50))

business_name
Meridian LLC                     83
Cedar LLC                        59
Slate LLC                        54
Sapphire LLC                     53
Atlas LLC                        53
Birch LLC                        52
Stag LLC                         52
Mumbai Private Limited Center    51
Ridgeline LLC                    50
Crestline LLC                    48
Zenith LLC                       48
Cornerstone LLC                  47
Compass LLC                      47
Meridian Inc                     47
Apex LLC                         47
Citadel LLC                      47
Beacon LLC                       46
Redwood LLC                      46
Amber LLC                        45
Kestrel LLC                      45
Titan LLC                        44
Everest LLC                      44
Aspen LLC                        44
Raven LLC                        43
Zephyr LLC                       43
Halcyon LLC                      43
Summit LLC                       42
Lyra LLC                         42
Sterling LLC                     42
Sequoia LLC                      42
Orion LLC                        42
Cardinal LLC                     42
Nova LLC                         42
Horizon LLC                      42
Anvil LLC                        41
Pinnacle LLC                     41
Cypress LLC                      41
Northwind LLC                    41
Lynx LLC                         41
Quartz LLC                       40
Cascade LLC                      40
Granite LLC                      40
Bastion LLC                      40
Jasper LLC                       40
Vertex LLC                       39
Monarch LLC                      39
Vanguard LLC                     39
Onyx LLC                         39
Willow LLC                       39
Basalt LLC                       38
Name: count, dtype: int64

In [59]:
for country in ["US", "India"]:
    print(f"\n===== {country} =====")
    
    temp = df[df["country"] == country]
    
    mask = temp["business_name"].str.contains(
        r'private|pvt|limited|ltd|corporation|corp|inc|incorporated|llc|llp',
        case=False,
        na=False,
        regex=True
    )
    
    print(temp.loc[mask, "business_name"].value_counts().head(20))

===== US =====
business_name
Meridian LLC       83
Cedar LLC          59
Slate LLC          54
Sapphire LLC       53
Atlas LLC          53
Birch LLC          52
Stag LLC           52
Ridgeline LLC      50
Crestline LLC      48
Zenith LLC         48
Cornerstone LLC    47
Compass LLC        47
Meridian Inc       47
Apex LLC           47
Citadel LLC        47
Beacon LLC         46
Redwood LLC        46
Amber LLC          45
Kestrel LLC        45
Titan LLC          44
Name: count, dtype: int64

===== India =====
business_name
Mumbai Private Limited Center       51
Shree Private Limited Center        37
Life Private Limited Center         34
Hotel Private Limited Center        34
Gold Private Limited Center         33
New Delhi Private Limited Center    32
Mumbai Private Limited Services     32
Jai Private Limited Center          32
Om Private Limited Center           32
Delhi Private Limited Center        32
Mumbai Pvt Ltd Center               30
Sai Private Limited Center          30
North Private Limited Center        30
New Private Limited Center          29
siprivate.com                       29
Digital Private Limited Services    28
Guru Private Limited Center         28
Dream Private Limited Center        28
Mumbai Limited Center               28
Perfect Private Limited Center      27
Name: count, dtype: int64

In [60]:
address_counts = df["business_address"].value_counts()

print(address_counts.head(30))

business_address
Ground Floor, Bangalore, KA                             29
Floor, Mumbai, MH                                       26
18, Kolkata, Howrah, WB                                 26
303, Mumbai, MH                                         25
12, Ahmedabad, GJ                                       23
101, Mumbai, Mumbai City, MH                            23
4, Mumbai, MH                                           23
Floor, Bangalore, KA                                    22
7, Kolkata, Howrah, WB                                  21
5, Ahmedabad, GJ                                        21
601, Mumbai, MH                                         21
301, Mumbai, Mumbai City, MH                            21
3, Ahmedabad, GJ                                        21
1, Kolkata, Howrah, WB                                  21
2, Mumbai, MH                                           20
10, Kolkata, Howrah, WB                                 20
2, Mumbai, Mumbai City, MH                              20
3, Kolkata, Howrah, WB                                  20
4, Kolkata, Howrah, WB                                  20
2, Kolkata, Howrah, WB                                  20
301, Mumbai, MH                                         19
1, Mumbai, MH                                           19
1, Chennai, TN                                          18
1948. Weaver Forest Way, Morrisville, North Carolina    18
1, Bangalore, KA                                        18
202, Mumbai, MH                                         18
5, Chennai, TN                                          18
Ground Floor, Mumbai, Mumbai City, MH                   18
16, Kolkata, Howrah, WB                                 18
102, Mumbai, Mumbai City, MH                            17
Name: count, dtype: int64

In [61]:
print(df["business_address"].dropna().sample(30, random_state=42).to_string(index=False))

                 781 Skyview Road, Salem, Virginia
Near Raunak Marriage Hall, Nalapar Afridiyan, R...
      123rd Ave, LKAE Stevens Township, Washington
447 Tranquila Drive, Camarillo Township, Califo...
              Morganton, 1254 Burkemont Avenue, NC
Keralam, Thirunakkra, Kottayam, Xii/74, First F...
Aligarh, #33 Panch Visa Jattari, Jatari, उत्तर ...
Gunjur, Door No 9245, Bangalore, KA, Gunjur Mai...
3490 Richpod-Rockfield Rd, Unit 6, Bowling Gree...
                   Sagecroft Drive, Houston, Texas
Hyderabad, Block-d, Maruthi Elite Gated Communi...
     2424 Heartstone Court, Clarksville, Tennessee
                230-234 3rd St, Ohio, Williamsburg
          Plot 300 244, Tilak Nagar, New Delhi, DL
708, Palms One, Royal Palms Estates Aarey Milk ...
46 Robert Ford Road, # 4, Watertown, Massachusetts
         916 Purple Moor Pass, Leanedr CITY, Texas
         16720 North Road, Martha Lake, Washington
           DL, Delhi, Wz-51a, First Floor Toda Pur
Hayatnagar, 3-53, Saroornagar, Sri Venkateswara...
                 508 8st St, Bucyrus, North Dakota
   #374 9-16-26, Vishakhapatnam, Visakhapatnam, AP
              Talwakars, Mahim, Mumbai, महाराष्ट्र
3031- Research Dr, PMB 5911, State College, Pen...
             380B Laneda Avenue, Manzanita, Oregon
12 Entire Basement And Ground Floor, New Delhi, DL
*Lien 1 Shop No 8 Tirupat, Complex Railway Road...
            Houston, Texas, #1614 Southmore Avenue
        1305 185th Dr, Goodyear, PMB 4324, Arizona
              5 West Street, <NULL>, Dellroy, Ohio

In [62]:
address_counts = df["business_address"].value_counts()

repeated_addresses = address_counts[
    address_counts >= 5
].head(20)

print(repeated_addresses)

business_address
Ground Floor, Bangalore, KA     29
Floor, Mumbai, MH               26
18, Kolkata, Howrah, WB         26
303, Mumbai, MH                 25
12, Ahmedabad, GJ               23
101, Mumbai, Mumbai City, MH    23
4, Mumbai, MH                   23
Floor, Bangalore, KA            22
7, Kolkata, Howrah, WB          21
5, Ahmedabad, GJ                21
601, Mumbai, MH                 21
301, Mumbai, Mumbai City, MH    21
3, Ahmedabad, GJ                21
1, Kolkata, Howrah, WB          21
2, Mumbai, MH                   20
10, Kolkata, Howrah, WB         20
2, Mumbai, Mumbai City, MH      20
3, Kolkata, Howrah, WB          20
4, Kolkata, Howrah, WB          20
2, Kolkata, Howrah, WB          20
Name: count, dtype: int64

In [63]:
df["name_basic"] = (
    df["business_name"]
    .str.lower()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

print(
    df[["business_name", "name_basic"]]
    .drop_duplicates()
    .head(30)
)

                                  business_name  \
0                            wilfordhancock.com
1   International South Consultants Private Ltd
2                   LLC Moncada Léarning Center
3                                Moyna's Coffee
4                  Pvt. EFS Print Ventures Ltd.
5                LLC Hernandez Colonial Redwood
6                 Classic Equity Partners Group
7                Ectolumdrex dba X+ Madison Inc
8                       Animal Hanisch Hospirlg
9                                 Gomez Optimal
10             The Rapid  Learning Alliance LLC
11                   Indian Care Public Limited
12                                        Béque
13                            #centraleducation
14          அரிஹந்த் Foundation Private Limited
15                          Wildlife Guild  LLC
16                           Cinder Charlton-PC
17                               ZRO Trinity Co
18            Bajaj Foundation  Private Limited
19                            Estell's Creative
20                           Center 5uperior Co
21                             Palace Vidyalaya
22                               Global Applied
23                 Integrated  Business Systems
24  Cardiology Heartland Cáre Associates #98825
25                    Sai  Surgical (India) Ltd
26  MW Management Private  Limited - 2067865001
27                         FERRERO FERRERO DUKE
28            Chinglepet Private Limited Center
29                       Modern Center Brothers

                                     name_basic
0                            wilfordhancock.com
1   international south consultants private ltd
2                   llc moncada léarning center
3                                moyna's coffee
4                  pvt. efs print ventures ltd.
5                llc hernandez colonial redwood
6                 classic equity partners group
7                ectolumdrex dba x+ madison inc
8                       animal hanisch hospirlg
9                                 gomez optimal
10              the rapid learning alliance llc
11                   indian care public limited
12                                        béque
13                            #centraleducation
14          அரிஹந்த் foundation private limited
15                           wildlife guild llc
16                           cinder charlton-pc
17                               zro trinity co
18             bajaj foundation private limited
19                            estell's creative
20                           center 5uperior co
21                             palace vidyalaya
22                               global applied
23                  integrated business systems
24  cardiology heartland cáre associates #98825
25                     sai surgical (india) ltd
26   mw management private limited - 2067865001
27                         ferrero ferrero duke
28            chinglepet private limited center
29                       modern center brothers

In [64]:
import unicodedata

def normalize_unicode(text):
    if pd.isna(text):
        return text
    
    return unicodedata.normalize("NFKC", text)

df["name_unicode"] = df["name_basic"].apply(normalize_unicode)

In [65]:
print(
    df[["business_name", "name_basic", "name_unicode"]]
    .drop_duplicates()
    .head(30)
)

                                  business_name  \
0                            wilfordhancock.com
1   International South Consultants Private Ltd
2                   LLC Moncada Léarning Center
3                                Moyna's Coffee
4                  Pvt. EFS Print Ventures Ltd.
5                LLC Hernandez Colonial Redwood
6                 Classic Equity Partners Group
7                Ectolumdrex dba X+ Madison Inc
8                       Animal Hanisch Hospirlg
9                                 Gomez Optimal
10             The Rapid  Learning Alliance LLC
11                   Indian Care Public Limited
12                                        Béque
13                            #centraleducation
14          அரிஹந்த் Foundation Private Limited
15                          Wildlife Guild  LLC
16                           Cinder Charlton-PC
17                               ZRO Trinity Co
18            Bajaj Foundation  Private Limited
19                            Estell's Creative
20                           Center 5uperior Co
21                             Palace Vidyalaya
22                               Global Applied
23                 Integrated  Business Systems
24  Cardiology Heartland Cáre Associates #98825
25                    Sai  Surgical (India) Ltd
26  MW Management Private  Limited - 2067865001
27                         FERRERO FERRERO DUKE
28            Chinglepet Private Limited Center
29                       Modern Center Brothers

                                     name_basic  \
0                            wilfordhancock.com
1   international south consultants private ltd
2                   llc moncada léarning center
3                                moyna's coffee
4                  pvt. efs print ventures ltd.
5                llc hernandez colonial redwood
6                 classic equity partners group
7                ectolumdrex dba x+ madison inc
8                       animal hanisch hospirlg
9                                 gomez optimal
10              the rapid learning alliance llc
11                   indian care public limited
12                                        béque
13                            #centraleducation
14          அரிஹந்த் foundation private limited
15                           wildlife guild llc
16                           cinder charlton-pc
17                               zro trinity co
18             bajaj foundation private limited
19                            estell's creative
20                           center 5uperior co
21                             palace vidyalaya
22                               global applied
23                  integrated business systems
24  cardiology heartland cáre associates #98825
25                     sai surgical (india) ltd
26   mw management private limited - 2067865001
27                         ferrero ferrero duke
28            chinglepet private limited center
29                       modern center brothers

                                   name_unicode
0                            wilfordhancock.com
1   international south consultants private ltd
2                   llc moncada léarning center
3                                moyna's coffee
4                  pvt. efs print ventures ltd.
5                llc hernandez colonial redwood
6                 classic equity partners group
7                ectolumdrex dba x+ madison inc
8                       animal hanisch hospirlg
9                                 gomez optimal
10              the rapid learning alliance llc
11                   indian care public limited
12                                        béque
13                            #centraleducation
14          அரிஹந்த் foundation private limited
15                           wildlife guild llc
16                           cinder charlton-pc
17                               zro trinity co
18             bajaj foundation private limited
19                            estell's creative
20                           center 5uperior co
21                             palace vidyalaya
22                               global applied
23                  integrated business systems
24  cardiology heartland cáre associates #98825
25                     sai surgical (india) ltd
26   mw management private limited - 2067865001
27                         ferrero ferrero duke
28            chinglepet private limited center
29                       modern center brothers

In [66]:
punctuation_mask = df["name_basic"].str.contains(
    r'[^\w\s]',
    regex=True,
    na=False
)

print("Names containing punctuation:",
      punctuation_mask.sum())

print("Percentage:",
      punctuation_mask.mean() * 100)

Names containing punctuation: 2119387
Percentage: 40.097355022690884

In [67]:
print(
    df.loc[
        punctuation_mask,
        "business_name"
    ].sample(30, random_state=42).to_string(index=False)
)

                आदित्य ऑल हॉस्पिटैलिटी प्रा. लि.
            Warren, Elliott and Love Ltd Service
                               Sai Sai [Academy]
                     Sanchez, Vikki, L.C.S.W. LP
                    ஜைன் அக்ரோ பிரைவேட் லிமிடெட்
                               A P & H Parts Llc
                ബാലാജി മീഡിയ പ്രൈവറ്റ് ലിമിറ്റഡ്
                        Newdelhitechnologies.Com
                               Helm Inc. Telecom
                                   Ironclad-Inc.
                          Om Construction L.L.P.
                            Masten & Sutton Inc.
                    Valerio's  Global Iron Works
             Chennai-Outsourcing Private Limited
        Noviyuma d/b/a Smith and Mejia Jaws Inc.
स्वस्तिक क्रिएटिव डेवलपर्स जनरल प्राइवेट लिमिटेड
                     Smt Mangal Global Pvt [Ltd]
                   Preferred-Media Partners Care
                       గుడ్ సాఫ్ట్‌వేర్ లిమిటెడ్
                                  Kesytnoe [Llc]
                      amf & sons private limited
                               Pvt. Air Eco Ltd.
         Priavnte Executive (India) Tech Limited
              स्मार्ट हेल्थकेयर प्राइवेट लिमिटेड
                                      fankle.com
                                   The Eye-Group
                   Evans's Metropolitan-Deli Inc
                           Becker, Mcginley  and
            Ariaquo Co f/k/a Capital Harvard LLC
                         Cardiology  Care L.L.C.

In [68]:
punctuation_mask = df["name_basic"].str.contains(
    r'[^\w\s]',
    regex=True,
    na=False
)

print("Names containing punctuation:",
      punctuation_mask.sum())

print("Percentage:",
      punctuation_mask.mean() * 100)

Names containing punctuation: 2119387
Percentage: 40.097355022690884

In [69]:
print(
    df.loc[
        punctuation_mask,
        "business_name"
    ].sample(30, random_state=42).to_string(index=False)
)

                आदित्य ऑल हॉस्पिटैलिटी प्रा. लि.
            Warren, Elliott and Love Ltd Service
                               Sai Sai [Academy]
                     Sanchez, Vikki, L.C.S.W. LP
                    ஜைன் அக்ரோ பிரைவேட் லிமிடெட்
                               A P & H Parts Llc
                ബാലാജി മീഡിയ പ്രൈവറ്റ് ലിമിറ്റഡ്
                        Newdelhitechnologies.Com
                               Helm Inc. Telecom
                                   Ironclad-Inc.
                          Om Construction L.L.P.
                            Masten & Sutton Inc.
                    Valerio's  Global Iron Works
             Chennai-Outsourcing Private Limited
        Noviyuma d/b/a Smith and Mejia Jaws Inc.
स्वस्तिक क्रिएटिव डेवलपर्स जनरल प्राइवेट लिमिटेड
                     Smt Mangal Global Pvt [Ltd]
                   Preferred-Media Partners Care
                       గుడ్ సాఫ్ట్‌వేర్ లిమిటెడ్
                                  Kesytnoe [Llc]
                      amf & sons private limited
                               Pvt. Air Eco Ltd.
         Priavnte Executive (India) Tech Limited
              स्मार्ट हेल्थकेयर प्राइवेट लिमिटेड
                                      fankle.com
                                   The Eye-Group
                   Evans's Metropolitan-Deli Inc
                           Becker, Mcginley  and
            Ariaquo Co f/k/a Capital Harvard LLC
                         Cardiology  Care L.L.C.

In [70]:
punctuation_mask = df["name_basic"].str.contains(
    r'[^\w\s]',
    regex=True,
    na=False
)

print("Names containing punctuation:", punctuation_mask.sum())
print("Percentage:", punctuation_mask.mean() * 100)

Names containing punctuation: 2119387
Percentage: 40.097355022690884

In [71]:
from collections import Counter 
punctuation_counts = Counter()
for value in df["name_basic"].dropna():
    punctuation_counts.update(
        char for char in value
        if not char.isalnum() and not char.isspace()
    )
print(punctuation_counts.most_common(30))

[('.', 1049958), (',', 440691), ('्', 402004), ('ि', 327606), ('-', 321853), ('े', 314792), ('(', 279139), (')', 279054), ('&', 218287), ('ा', 189303), ('[', 166024), (']', 166023), ('్', 143572), ('್', 137555), ('/', 123526), ('்', 115238), ("'", 101889), ('ं', 96627), ('്', 80855), ('ி', 65790), ('ी', 63999), ('્', 55037), ('ಿ', 54059), ('ి', 50301), ('*', 49188), ('ি', 46970), ('ो', 46250), ('্', 43884), ('ে', 40689), ('া', 38518)]

In [72]:
chars = [".", "-", "&", "'", "/", "#", "(", ")", "[", "]", "+"]

for char in chars:
    mask = df["name_basic"].str.contains(
        "\\" + char if char in r"\.^$*+?{}[]|()" else char,
        regex=True,
        na=False
    )
    
    print(f"\n===== {char} =====")
    print(df.loc[mask, "business_name"].head(10).to_string(index=False))

===== . =====
               wilfordhancock.com
     Pvt. EFS Print Ventures Ltd.
      Shree Sgpeciarity Pvt. Ltd.
                      Hmgreen.Com
                    TV Tower Inc.
erwinsignaturekrakacquisition.com
          Basalt Forefront L.L.C.
      Hyacinthe L. Cheung D.C. PC
            Bonnettresilience.Com
                           7m.com

===== - =====
                         Cinder Charlton-PC
MW Management Private  Limited - 2067865001
      Capital-Snow Capital-Snow Corporation
              Mr Om-Consultants Corporation
            lakshmi medical-mumbai ventures
    Mr Chalakudy-+ Partners Private Limited
  Solutions Accuracy Healthcare-Private Ltd
                   -- Maryl-Khalil Old Corp
                     Germana Ott Slaect-Oyj
            Shaffer Xcblla LLC - 7934786696

===== & =====
              Ear N0se & Throat Regional
Bennett & Mofcno Canary of Liverpoo1 Ltd
        Mclaughlin, Blanco  & Walker Ltd
    Insightful & Sons Industries Limited
 Morales, Godina & Pánkow Associates LLC
      Campus & Brothers Phiavte  Limited
Day, Marsh Marsh & Stone Fortunex L.L.C.
              Snyder & Martinez Emerging
          Martinez, Harris & Guevara Llc
        Garcia,  Fergus0n & Meadows PLLC

===== ' =====
                       Moyna's Coffee
                    Estell's Creative
                Compher's Auto  Glass
   Karo1's Capital Restaurant  Clginc
Belocalo Co fka Deleon's Select Pizza
      Jeri'S Frontier Fitness Central
                 Cherry's Stár Coffee
  Lakeside Colonial Holdings Gertie's
        Leonelle's Elite Nails (Inc.)
                  Diana's Hospitality

===== / =====
                       M/s Jd Pvt Ltd Services
             Quonex d/b/a M D Herrera Offshore
M/s Basera Advisors  Group | www.baseraadv.com
      M/s shiny medical centre private limited
         Fayesyn F/K/A All Dynamic Telecom LLC
                  M/s Galaxy Solutions Pvt Ltd
    M/s Shree Management Steel Private Limited
               M/s Green Civil (India) Private
             M/s Smart Foods Pdrivaet  Limited
                     Veolumx t/a Teum Holdings

===== # =====
                          #centraleducation
Cardiology Heartland Cáre Associates #98825
                             #Apexphotonics
                          #ironworkerslocal
                                #8 Services
                #76062 Quality Antimony-Inc
           Eastern Holdings Services #91960
            cthrinespeakwellness.com #64913
                         #Robertsonpiedmont
                                  #clemmiej

===== ( =====
                   Sai  Surgical (India) Ltd
   The Consultants Karnataka Cotex (Limited)
          Ken Hospitalities (India)  Limited
                    Jsg Enterprises (Center)
                      Tu Ventures  Pvt (Ltd)
                (Ltd) Producer Aim Solutions
       Violet (lndia) Infotech Praei Limited
                            Smith (Software)
              Audio Agrotech  (India) L.L.P.
Brightmoon Builders-(gdngai) Private Limited

===== ) =====
                   Sai  Surgical (India) Ltd
   The Consultants Karnataka Cotex (Limited)
          Ken Hospitalities (India)  Limited
                    Jsg Enterprises (Center)
                      Tu Ventures  Pvt (Ltd)
                (Ltd) Producer Aim Solutions
       Violet (lndia) Infotech Praei Limited
                            Smith (Software)
              Audio Agrotech  (India) L.L.P.
Brightmoon Builders-(gdngai) Private Limited

===== [ =====
                  Raj Black [Marketing]
                        Clear [Payroll]
      Private Shivam Projects [Limited]
Finance Divya Balaji  Private [Limited]
              Akridge Family [Practice]
                     Empire Rithm [LLC]
        Penny A. Lind, DPM, PC [Harbor]
                       White lnfra [Co]
     Apex Consultancy Private [Limited]
                      Duncan [Boutique]

===== ] =====
                  Raj Black [Marketing]
                        Clear [Payroll]
      Private Shivam Projects [Limited]
Finance Divya Balaji  Private [Limited]
              Akridge Family [Practice]
                     Empire Rithm [LLC]
        Penny A. Lind, DPM, PC [Harbor]
                       White lnfra [Co]
     Apex Consultancy Private [Limited]
                      Duncan [Boutique]

===== + =====
         Ectolumdrex dba X+ Madison Inc
         Stellar + Brothers Private Ltd
Mr Chalakudy-+ Partners Private Limited
                             O+ Fortune
           Pvt Marutham + Bsrorhers Ltd
                      N+-Teocufiuo, Inc
                         D + P Painting
  Miller, Wright + Vaaalas Montreal Inc
                          H+-Inc Center
                   Avighna + + Brcthers

In [73]:
def has_non_ascii(text):
    if pd.isna(text):
        return False
    return any(ord(char)>127 for char in text)
non_ascii_mask=df["business_name"].apply(has_non_ascii)
print("Names containing non-ASCII characters:",non_ascii_mask.sum())
print("Percentage:",non_ascii_mask.mean()*100)

Names containing non-ASCII characters: 606737
Percentage: 11.479049788642847

In [74]:
print(
    df.loc[
        non_ascii_mask,
        "business_name"
    ].sample(30,
random_state=42).to_string(index=False)
)

                                Asim & Pártners
           Red Krlrhná Builders Private Limited
        यूनिवर्सल एंटरप्राइजेज प्राइवेट लिमिटेड
                   ബാലാജി കൺസ്ട്രക്ഷൻ ലിമിറ്റഡ്
             Signature-Metropolitan Reserve Ínc
             ଜୈନ ହସ୍ପିଟାଲିଟି ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
    ক্রিয়েটিভ ইনভেস্টমেন্টস টেক্সটাইলস লিমিটেড
                     Obrien Bright Winvest, Ínc
                              ੴ ਇਸਟੇਟ ਪ੍ਰਾ. ਲਿ.
                          श्री इम्पेक्स लिमिटेड
                   इनोवेटिव एंटरप्राइजेज एलएलपी
                    Pvt Prama Ínnovations [Ltd]
                           Lower Áermiacn-Grupo
             সান ট্রেডিং হোটেল প্রাইভেট লিমিটেড
                            अरिहंत एंटरप्राइजेज
     બોમ્બે લક્ષ્મી પ્રોપર્ટીઝ પ્રાઇવેટ લિમિટેડ
    Wexriza Labs née Rajesh Educational Society
         Fortune Good Lógistics Private Limited
                            Loe Hómes of #30163
        Private Omkar Tráding Infratech Limited
                  Tetra Cónsultancy Enterprises
                           ఈస్ట్ ఐటీ ఎల్‌ఎల్‌పీ
ಗ್ಯಾಲಕ್ಸಿ ಗ್ಯಾಲಕ್ಸಿ ಟೆಕ್ನಾಲಜಿ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
          ହୋଟେଲ୍ କନସଲଟାଣ୍ଟସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
              ગ્રેટ ટેક્નોલોજી પ્રાઇવેટ લિમિટેડ
                       Hunger Sóciety VI #94976
            ક્રિષ્ના ફાઉન્ડેશન પ્રાઇવેટ લિમિટેડ
            ಬ್ಲ್ಯಾಕ್ ಇಂಪೆಕ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
                     ड्रीम कंस्ट्रक्शंस लिमिटेड
               క్రియేటివ్ ఐటీ ప్రైవేట్ లిమిటెడ్

In [75]:
import unicodedata

def normalize_unicode(text):
    if pd.isna(text):
        return text
    return unicodedata.normalize("NFKC", text)

df["name_unicode"] = df["name_basic"].map(normalize_unicode)

In [76]:
changed = (
    df["name_basic"].fillna("") !=
    df["name_unicode"].fillna("")
)

print("Names changed by Unicode normalization:", changed.sum())

Names changed by Unicode normalization: 0

In [77]:
print(
    df.loc[
        changed,
        ["business_name", "name_basic", "name_unicode"]
    ].head(30).to_string(index=False)
)

Empty DataFrame
Columns: [business_name, name_basic, name_unicode]
Index: []

In [78]:
legal_patterns = {
    "LLC": r"\bL\.?L\.?C\.?\b",
    "INC": r"\bI\.?N\.?C\.?\b",
    "LTD": r"\bL\.?T\.?D\.?\b",
    "CORP": r"\bC\.?O\.?R\.?P\.?\b",
    "CORPORATION": r"\bCORPORATION\b",
    "PRIVATE LIMITED": r"\bPRIVATE\s+LIMITED\b",
    "PVT LTD": r"\bPVT\.?\s+LTD\.?\b",
    "LLP": r"\bL\.?L\.?P\.?\b",
}

for label, pattern in legal_patterns.items():
    mask = df["name_basic"].str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    )
    
    print(f"{label:20} {mask.sum():,}")

LLC                  637,471
INC                  419,917
LTD                  427,781
CORP                 140,236
CORPORATION          58,097
PRIVATE LIMITED      304,033
PVT LTD              131,387
LLP                  89,535

In [79]:
suffix_patterns = {
    "LLC": r"\bL\.?L\.?C\.?\s*$",
    "INC": r"\bI\.?N\.?C\.?\s*$",
    "LTD": r"\bL\.?T\.?D\.?\s*$",
    "CORP": r"\bC\.?O\.?R\.?P\.?\s*$",
    "CORPORATION": r"\bCORPORATION\s*$",
    "PRIVATE LIMITED": r"\bPRIVATE\s+LIMITED\s*$",
    "PVT LTD": r"\bPVT\.?\s+LTD\.?\s*$",
    "LLP": r"\bL\.?L\.?P\.?\s*$",
}

for label, pattern in suffix_patterns.items():
    mask = df["name_basic"].str.contains(
        pattern,
        case=False,
        regex=True,
        na=False
    )
    
    print(f"{label:20} {mask.sum():,}")

LLC                  468,065
INC                  311,180
LTD                  345,934
CORP                 108,141
CORPORATION          46,471
PRIVATE LIMITED      266,099
PVT LTD              110,740
LLP                  65,340

In [80]:
suffix_patterns = {
    "LLC": r"\bL\.?L\.?C\.?\s*$",
    "INC": r"\bI\.?N\.?C\.?\s*$",
    "LTD": r"\bL\.?T\.?D\.?\s*$",
    "CORP": r"\bC\.?O\.?R\.?P\.?\s*$",
    "CORPORATION": r"\bCORPORATION\s*$",
    "PRIVATE LIMITED": r"\bPRIVATE\s+LIMITED\s*$",
    "PVT LTD": r"\bPVT\.?\s+LTD\.?\s*$",
    "LLP": r"\bL\.?L\.?P\.?\s*$",
}

df["legal_form"] = pd.NA

for label, pattern in suffix_patterns.items():
    mask = (
        df["legal_form"].isna()
        & df["name_basic"].str.contains(
            pattern,
            case=False,
            regex=True,
            na=False
        )
    )
    
    df.loc[mask, "legal_form"] = label

In [81]:
print(df["legal_form"].value_counts(dropna=False))

legal_form
<NA>               3674373
LLC                 468065
LTD                 345934
INC                 311180
PRIVATE LIMITED     266099
CORP                108141
LLP                  65340
CORPORATION          46471
Name: count, dtype: int64

In [82]:
print(
    df.loc[
        df["legal_form"].notna(),
        ["business_name", "name_basic", "legal_form"]
    ].sample(30, random_state=42).to_string(index=False)
)

                                      business_name                                          name_basic      legal_form
                          K 7 Classic Painting Inc.                           k 7 classic painting inc.             INC
                M/s Surya Logistics Private Limited                 m/s surya logistics private limited PRIVATE LIMITED
                                          Mivue LLC                                           mivue llc             LLC
Brixhalohalox doing business as Nexmiia Corporation brixhalohalox doing business as nexmiia corporation     CORPORATION
              Smt UNITED INDUSTRIES PRIVATE LIMITED               smt united industries private limited PRIVATE LIMITED
                         Lampley Desert Vornado Llc                          lampley desert vornado llc             LLC
             Diversified Digital  Wcolrdwide L.L.C.               diversified digital wcolrdwide l.l.c.             LLC
                     Classic International Pvt Ltd.                      classic international pvt ltd.             LTD
                        Ludovika-Clay Márketing Ltd                         ludovika-clay márketing ltd             LTD
           Mr Krimson Mánufacturing Private Limited            mr krimson mánufacturing private limited PRIVATE LIMITED
                          హోటల్ ఐటీ Private Limited                           హోటల్ ఐటీ private limited PRIVATE LIMITED
                      Great Consultants Private Ltd                       great consultants private ltd             LTD
                                Patriot Gtahrer Inc                                 patriot gtahrer inc             INC
                  Babbie Keestgrson Diagnostics LLC                   babbie keestgrson diagnostics llc             LLC
                     >> Ace  Education Advisors Ltd                       >> ace education advisors ltd             LTD
                                Patriot Genesis LTD                                 patriot genesis ltd             LTD
                                   Dynamic  Pmv Ltd                                     dynamic pmv ltd             LTD
        Universal Software Hardware Private Limited         universal software hardware private limited PRIVATE LIMITED
                              Fab India Private Ltd                               fab india private ltd             LTD
                         Pinnacle Digital Cocts LLC                          pinnacle digital cocts llc             LLC
                      Upper Valley Providence, Ltd.                       upper valley providence, ltd.             LTD
                    GE Advacheemont Private Limited                     ge advacheemont private limited PRIVATE LIMITED
         Surya Finance  Electronics Private Limited           surya finance electronics private limited PRIVATE LIMITED
                          mccoy rent of ballwin llc                           mccoy rent of ballwin llc             LLC
                      Dream Scotare Private Limited                       dream scotare private limited PRIVATE LIMITED
                        Delhi  Well Private Limited                          delhi well private limited PRIVATE LIMITED
     SUBHSHREE INFOTECH ENTERPRISES PRIVATE LIMITED      subhshree infotech enterprises private limited PRIVATE LIMITED
      Ayanna Entertainment (India)  Private Limited        ayanna entertainment (india) private limited PRIVATE LIMITED
                               Colombo Medical  LLC                                 colombo medical llc             LLC
                             Midwest All Vulcan Llc                              midwest all vulcan llc             LLC

In [83]:
suffix_patterns = [
    ("PRIVATE LIMITED", r"\bPRIVATE\s+L(?:IMITED|TD\.?)\s*$"),
    ("PVT LTD", r"\bPVT\.?\s+L(?:TD|IMITED)\.?\s*$"),
    ("CORPORATION", r"\bCORPORATION\s*$"),
    ("LLC", r"\bL\.?L\.?C\.?\s*$"),
    ("LLP", r"\bL\.?L\.?P\.?\s*$"),
    ("INC", r"\bI\.?N\.?C\.?\s*$"),
    ("CORP", r"\bC\.?O\.?R\.?P\.?\s*$"),
    ("LTD", r"\bL\.?T\.?D\.?\s*$"),
]

df["legal_form"] = pd.NA

for label, pattern in suffix_patterns:
    mask = (
        df["legal_form"].isna()
        & df["name_basic"].str.contains(
            pattern,
            regex=True,
            na=False
        )
    )
    df.loc[mask, "legal_form"] = label

In [84]:
print(df["legal_form"].value_counts(dropna=False))

legal_form
<NA>    5285603
Name: count, dtype: int64

In [85]:
suffix_patterns = [
    ("PRIVATE LIMITED", r"\bPRIVATE\s+L(?:IMITED|TD\.?)\s*$"),
    ("PVT LTD", r"\bPVT\.?\s+L(?:TD|IMITED)\.?\s*$"),
    ("CORPORATION", r"\bCORPORATION\s*$"),
    ("LLC", r"\bL\.?L\.?C\.?\s*$"),
    ("LLP", r"\bL\.?L\.?P\.?\s*$"),
    ("INC", r"\bI\.?N\.?C\.?\s*$"),
    ("CORP", r"\bC\.?O\.?R\.?P\.?\s*$"),
    ("LTD", r"\bL\.?T\.?D\.?\s*$"),
]

df["legal_form"] = pd.NA

for label, pattern in suffix_patterns:
    mask = (
        df["legal_form"].isna()
        & df["name_basic"].str.contains(
            pattern,
            case=False,
            regex=True,
            na=False
        )
    )
    df.loc[mask, "legal_form"] = label

In [86]:
print(df["legal_form"].value_counts(dropna=False))

legal_form
<NA>               3662372
LLC                 468065
PRIVATE LIMITED     347076
INC                 311180
LTD                 154217
PVT LTD             122741
CORP                108141
LLP                  65340
CORPORATION          46471
Name: count, dtype: int64

In [87]:
examples = [
    "Classic International Pvt Ltd.",
    "Fab India Private Ltd",
    "M/s Surya Logistics Private Limited",
    "Mivue LLC",
    "Patriot Genesis LTD"
]

print(
    df[df["business_name"].isin(examples)]
    [["business_name", "legal_form"]]
    .to_string(index=False)
)

                      business_name      legal_form
     Classic International Pvt Ltd.         PVT LTD
                Patriot Genesis LTD             LTD
     Classic International Pvt Ltd.         PVT LTD
                          Mivue LLC             LLC
                          Mivue LLC             LLC
M/s Surya Logistics Private Limited PRIVATE LIMITED
                          Mivue LLC             LLC
              Fab India Private Ltd PRIVATE LIMITED
                          Mivue LLC             LLC
                          Mivue LLC             LLC
                          Mivue LLC             LLC
                          Mivue LLC             LLC
                          Mivue LLC             LLC

In [88]:
df["name_core"] = df["name_basic"]

for label, pattern in suffix_patterns:
    mask = df["legal_form"].eq(label)
    
    df.loc[mask, "name_core"] = (
        df.loc[mask, "name_basic"]
        .str.replace(pattern, "", regex=True)
        .str.strip()
    )

In [89]:
print(
    df.loc[
        df["legal_form"].notna(),
        ["business_name", "name_core", "legal_form"]
    ].sample(30, random_state=42).to_string(index=False)
)

                                   business_name                                        name_core      legal_form
        Rosemaria Mogquin Diamond Generation Inc         rosemaria mogquin diamond generation inc             INC
                                       Stag Inc.                                        stag inc.             INC
                   Kati Baar Legacy Wellness-Inc                    kati baar legacy wellness-inc             INC
   Toledo Bhcftíoral Health Precision Center Ltd    toledo bhcftíoral health precision center ltd             LTD
                                     Foundry LLC                                      foundry llc             LLC
          Raj Ínvestment General Private Limited           raj ínvestment general private limited PRIVATE LIMITED
                           EYE DIRECT CENTER INC                            eye direct center inc             INC
                            Atlantic Ácademy LLC                             atlantic ácademy llc             LLC
                            Trudi's  Couture Inc                              trudi's couture inc             INC
                            Pvt Prayas Cargo Ltd                             pvt prayas cargo ltd             LTD
                   Bay Empire Electronic LLC LLC                    bay empire electronic llc llc             LLC
                    Shree & Scns Private Limited                     shree & scns private limited PRIVATE LIMITED
                         Martinez Ddohecgon Corp                          martinez ddohecgon corp            CORP
 Lavanya (India) (India) Traders Private Limited  lavanya (india) (india) traders private limited PRIVATE LIMITED
          Miraveoio doing business as Zephyr LLC           miraveoio doing business as zephyr llc             LLC
Kathryn Williams Tri-State Home Improvements Inc kathryn williams tri-state home improvements inc             INC
                      Smt Steam Ventures Pvt Ltd                       smt steam ventures pvt ltd         PVT LTD
                             Center Frontier LLC                              center frontier llc             LLC
                          Coex  Great Stores Inc                            coex great stores inc             INC
       Creators (Inhdia) Benefit Private Limited        creators (inhdia) benefit private limited PRIVATE LIMITED
               Mr one foundation private limited                mr one foundation private limited PRIVATE LIMITED
           Solsol DBA Boteca Holding Company LLC            solsol dba boteca holding company llc             LLC
                          Main Street Coffee LLC                           main street coffee llc             LLC
                        ER Laank Private Limited                         er laank private limited PRIVATE LIMITED
             Delhi Manufacturers-Private Limited              delhi manufacturers-private limited PRIVATE LIMITED
                                 Sweet-Cafe Inc.                                  sweet-cafe inc.             INC
                        Holy Church Partners LLC                         holy church partners llc             LLC
                  Long, Holmes & Barnes-Lake LLC                   long, holmes & barnes-lake llc             LLC
      Golden Technologies (India)Private Limited       golden technologies (india)private limited PRIVATE LIMITED
                           Tucker Star Ze0  Corp                             tucker star ze0 corp            CORP

In [90]:
df["name_core"] = df["name_basic"]

for label, pattern in suffix_patterns:
    mask = df["legal_form"].eq(label)
    
    df.loc[mask, "name_core"] = (
        df.loc[mask, "name_basic"]
        .str.replace(
            pattern,
            "",
            regex=True,
            case=False
        )
        .str.strip()
    )

In [91]:
print(
    df.loc[
        df["legal_form"].notna(),
        ["business_name", "name_core", "legal_form"]
    ].sample(30, random_state=42).to_string(index=False)
)

                                   business_name                                    name_core      legal_form
        Rosemaria Mogquin Diamond Generation Inc         rosemaria mogquin diamond generation             INC
                                       Stag Inc.                                         stag             INC
                   Kati Baar Legacy Wellness-Inc                   kati baar legacy wellness-             INC
   Toledo Bhcftíoral Health Precision Center Ltd    toledo bhcftíoral health precision center             LTD
                                     Foundry LLC                                      foundry             LLC
          Raj Ínvestment General Private Limited                       raj ínvestment general PRIVATE LIMITED
                           EYE DIRECT CENTER INC                            eye direct center             INC
                            Atlantic Ácademy LLC                             atlantic ácademy             LLC
                            Trudi's  Couture Inc                              trudi's couture             INC
                            Pvt Prayas Cargo Ltd                             pvt prayas cargo             LTD
                   Bay Empire Electronic LLC LLC                    bay empire electronic llc             LLC
                    Shree & Scns Private Limited                                 shree & scns PRIVATE LIMITED
                         Martinez Ddohecgon Corp                           martinez ddohecgon            CORP
 Lavanya (India) (India) Traders Private Limited              lavanya (india) (india) traders PRIVATE LIMITED
          Miraveoio doing business as Zephyr LLC           miraveoio doing business as zephyr             LLC
Kathryn Williams Tri-State Home Improvements Inc kathryn williams tri-state home improvements             INC
                      Smt Steam Ventures Pvt Ltd                           smt steam ventures         PVT LTD
                             Center Frontier LLC                              center frontier             LLC
                          Coex  Great Stores Inc                            coex great stores             INC
       Creators (Inhdia) Benefit Private Limited                    creators (inhdia) benefit PRIVATE LIMITED
               Mr one foundation private limited                            mr one foundation PRIVATE LIMITED
           Solsol DBA Boteca Holding Company LLC            solsol dba boteca holding company             LLC
                          Main Street Coffee LLC                           main street coffee             LLC
                        ER Laank Private Limited                                     er laank PRIVATE LIMITED
             Delhi Manufacturers-Private Limited                         delhi manufacturers- PRIVATE LIMITED
                                 Sweet-Cafe Inc.                                   sweet-cafe             INC
                        Holy Church Partners LLC                         holy church partners             LLC
                  Long, Holmes & Barnes-Lake LLC                   long, holmes & barnes-lake             LLC
      Golden Technologies (India)Private Limited                  golden technologies (india) PRIVATE LIMITED
                           Tucker Star Ze0  Corp                              tucker star ze0            CORP

In [92]:
print("Raw unique names:",
      df["business_name"].nunique())

print("Basic normalized unique names:",
      df["name_basic"].nunique())

print("Core names unique:",
      df["name_core"].nunique())

Raw unique names: 4651608
Basic normalized unique names: 4473473
Core names unique: 4195931

In [93]:
print("Raw duplicate rows:",
      len(df) - df["business_name"].nunique())

print("Basic-normalized duplicate rows:",
      len(df) - df["name_basic"].nunique())

print("Core-name duplicate rows:",
      len(df) - df["name_core"].nunique())

Raw duplicate rows: 633995
Basic-normalized duplicate rows: 812130
Core-name duplicate rows: 1089672

In [94]:
core_counts = (
    df["name_core"]
    .value_counts()
)

print(core_counts.head(30))

name_core
primary care           482
meridian               479
physical therapy       477
pediatric dental       469
urgent care            455
womens health          438
pediatric dentistry    429
behavioral health      396
internal medicine      395
summit                 364
apex                   360
pediatric              351
cascade                343
family center          332
cedar                  318
sterling               313
vanguard               308
earnosethroat.com      307
pinnacle               306
cornerstone            299
lynx                   299
helios                 294
anchor                 294
horizon                294
the dent               290
straight edge          286
foot & ankle           284
aspen                  283
granite                283
beacon                 279
Name: count, dtype: int64

In [95]:
pd.set_option("display.max_rows", 50)

df[["business_name", "name_basic", "legal_form", "name_core"]].head(50)

,business_name,name_basic,legal_form,name_core
0,wilfordhancock.com,wilfordhancock.com,<NA>,wilfordhancock.com
1,International South Consultants Private Ltd,international south consultants private ltd,PRIVATE LIMITED,international south consultants
2,LLC Moncada Léarning Center,llc moncada léarning center,<NA>,llc moncada léarning center
3,Moyna's Coffee,moyna's coffee,<NA>,moyna's coffee
4,Pvt. EFS Print Ventures Ltd.,pvt. efs print ventures ltd.,LTD,pvt. efs print ventures
5,LLC Hernandez Colonial Redwood,llc hernandez colonial redwood,<NA>,llc hernandez colonial redwood
6,Classic Equity Partners Group,classic equity partners group,<NA>,classic equity partners group
7,Ectolumdrex dba X+ Madison Inc,ectolumdrex dba x+ madison inc,INC,ectolumdrex dba x+ madison
8,Animal Hanisch Hospirlg,animal hanisch hospirlg,<NA>,animal hanisch hospirlg
9,Gomez Optimal,gomez optimal,<NA>,gomez optimal
10,The Rapid Learning Alliance LLC,the rapid learning alliance llc,LLC,the rapid learning alliance
11,Indian Care Public Limited,indian care public limited,<NA>,indian care public limited
12,Béque,béque,<NA>,béque
13,#centraleducation,#centraleducation,<NA>,#centraleducation
14,அரிஹந்த் Foundation Private Limited,அரிஹந்த் foundation private limited,PRIVATE LIMITED,அரிஹந்த் foundation
15,Wildlife Guild LLC,wildlife guild llc,LLC,wildlife guild
16,Cinder Charlton-PC,cinder charlton-pc,<NA>,cinder charlton-pc
17,ZRO Trinity Co,zro trinity co,<NA>,zro trinity co
18,Bajaj Foundation Private Limited,bajaj foundation private limited,PRIVATE LIMITED,bajaj foundation
19,Estell's Creative,estell's creative,<NA>,estell's creative
20,Center 5uperior Co,center 5uperior co,<NA>,center 5uperior co
21,Palace Vidyalaya,palace vidyalaya,<NA>,palace vidyalaya
22,Global Applied,global applied,<NA>,global applied
23,Integrated Business Systems,integrated business systems,<NA>,integrated business systems
24,Cardiology Heartland Cáre Associates #98825,cardiology heartland cáre associates #98825,<NA>,cardiology heartland cáre associates #98825
25,Sai Surgical (India) Ltd,sai surgical (india) ltd,LTD,sai surgical (india)
26,MW Management Private Limited - 2067865001,mw management private limited - 2067865001,<NA>,mw management private limited - 2067865001
27,FERRERO FERRERO DUKE,ferrero ferrero duke,<NA>,ferrero ferrero duke
28,Chinglepet Private Limited Center,chinglepet private limited center,<NA>,chinglepet private limited center
29,Modern Center Brothers,modern center brothers,<NA>,modern center brothers
30,Navkar Sons Ltd Center,navkar sons ltd center,<NA>,navkar sons ltd center
31,സിൽവർ കൺസൾട്ടൻസി പ്രൈവറ്റ് ലിമിറ്റഡ്,സിൽവർ കൺസൾട്ടൻസി പ്രൈവറ്റ് ലിമിറ്റഡ്,<NA>,സിൽവർ കൺസൾട്ടൻസി പ്രൈവറ്റ് ലിമിറ്റഡ്
32,ब्लू टेक्नोलॉजीज,ब्लू टेक्नोलॉजीज,<NA>,ब्लू टेक्नोलॉजीज
33,Compher's Auto Glass,compher's auto glass,<NA>,compher's auto glass
34,గుజరాత్ Logistics లిమిటెడ్,గుజరాత్ logistics లిమిటెడ్,<NA>,గుజరాత్ logistics లిమిటెడ్
35,Stellar + Brothers Private Ltd,stellar + brothers private ltd,PRIVATE LIMITED,stellar + brothers
36,Ear N0se & Throat Regional,ear n0se & throat regional,<NA>,ear n0se & throat regional
37,"Best Software Innovations,","best software innovations,",<NA>,"best software innovations,"
38,Capital-Snow Capital-Snow Corporation,capital-snow capital-snow corporation,CORPORATION,capital-snow capital-snow
39,SAV Holdings,sav holdings,<NA>,sav holdings
40,Mr Om-Consultants Corporation,mr om-consultants corporation,CORPORATION,mr om-consultants
41,Cozy Shop Bike,cozy shop bike,<NA>,cozy shop bike
42,LLC Safe Newbury,llc safe newbury,<NA>,llc safe newbury
43,Shree Sgpeciarity Pvt. Ltd.,shree sgpeciarity pvt. ltd.,PVT LTD,shree sgpeciarity
44,Little Ice Cirhm,little ice cirhm,<NA>,little ice cirhm
45,Hmgreen.Com,hmgreen.com,<NA>,hmgreen.com
46,TV Tower Inc.,tv tower inc.,INC,tv tower
47,lakshmi medical-mumbai ventures,lakshmi medical-mumbai ventures,<NA>,lakshmi medical-mumbai ventures
48,Orthopedic Specialists Of Fort Wht LLC,orthopedic specialists of fort wht llc,LLC,orthopedic specialists of fort wht
49,erwinsignaturekrakacquisition.com,erwinsignaturekrakacquisition.com,<NA>,erwinsignaturekrakacquisition.com

In [96]:
df["address_basic"] = (
    df["business_address"]
    .str.lower()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [97]:
df[["business_address", "address_basic"]].sample(20)

,business_address,address_basic
4120875,"Flat 2-01, 3Rd Floor, Lahari Grand Ville, Naga...","flat 2-01, 3rd floor, lahari grand ville, naga..."
1895614,"34-16-50, First Floor, Mandapet-533 308. 533 3...","34-16-50, first floor, mandapet-533 308. 533 3..."
1672201,NaN,NaN
3626711,"00728 St James Pl, Molalla, Oregon","00728 st james pl, molalla, oregon"
5244536,"#1/26 Housing Board, 1St Floor, Sriganganagar,...","#1/26 housing board, 1st floor, sriganganagar,..."
5240700,"0424 2A Main Street, Ottawa, Illinois","0424 2a main street, ottawa, illinois"
5247087,"##21, Arya Samaj Road Karol Bagh, Delhi, DL","##21, arya samaj road karol bagh, delhi, dl"
2233888,"19385 Big Creek Road, Shell Knob, MO","19385 big creek road, shell knob, mo"
3920357,"Jayanti Nawal Niwas, 201-A, Flat No-03, Phulwa...","jayanti nawal niwas, 201-a, flat no-03, phulwa..."
3268410,"DC, Unit 107, Washington, 1355 Peabody Street","dc, unit 107, washington, 1355 peabody street"
332583,"#0016/2, 1St Cross, 1St Main, Cambridge Layout...","#0016/2, 1st cross, 1st main, cambridge layout..."
3810017,"4909 Middleton Ln, Huntsville, Alabama","4909 middleton ln, huntsville, alabama"
5006522,"134 Madson Avenue, # Suite 3, Albany, New York","134 madson avenue, # suite 3, albany, new york"
152031,"160 Main Street, Unit B, Hatfield, MA","160 main street, unit b, hatfield, ma"
538144,"Reliance Street, Charlotte, North Carolina","reliance street, charlotte, north carolina"
3578421,"18220 121st Street, Arlington, Washington","18220 121st street, arlington, washington"
3349,"No 335- 222, Gurgaon, हरियाणा","no 335- 222, gurgaon, हरियाणा"
956394,"Nebraska, 3028 68th Ct, Omaha","nebraska, 3028 68th ct, omaha"
4467461,"102 Mulberry Drive, Missouri, Camdenton","102 mulberry drive, missouri, camdenton"
808050,"963-D 6st Ave, N/A, Mills, Wyoming","963-d 6st ave, n/a, mills, wyoming"

In [98]:
print("Raw unique addresses:",
      df["business_address"].nunique())

print("Basic normalized unique addresses:",
      df["address_basic"].nunique())

print("Raw duplicate rows:",
      len(df) - df["business_address"].nunique())

print("Basic-normalized duplicate rows:",
      len(df) - df["address_basic"].nunique())

Raw unique addresses: 4632764
Basic normalized unique addresses: 4631187
Raw duplicate rows: 652839
Basic-normalized duplicate rows: 654416

In [99]:
df["address_basic"].value_counts().head(30)

address_basic
ground floor, bangalore, ka                             29
floor, mumbai, mh                                       26
18, kolkata, howrah, wb                                 26
303, mumbai, mh                                         25
12, ahmedabad, gj                                       23
101, mumbai, mumbai city, mh                            23
4, mumbai, mh                                           23
floor, bangalore, ka                                    22
7, kolkata, howrah, wb                                  21
5, ahmedabad, gj                                        21
601, mumbai, mh                                         21
301, mumbai, mumbai city, mh                            21
3, ahmedabad, gj                                        21
1, kolkata, howrah, wb                                  21
2, mumbai, mh                                           20
10, kolkata, howrah, wb                                 20
2, mumbai, mumbai city, mh                              20
3, kolkata, howrah, wb                                  20
4, kolkata, howrah, wb                                  20
2, kolkata, howrah, wb                                  20
301, mumbai, mh                                         19
1, mumbai, mh                                           19
1, chennai, tn                                          18
1948. weaver forest way, morrisville, north carolina    18
1, bangalore, ka                                        18
202, mumbai, mh                                         18
5, chennai, tn                                          18
ground floor, mumbai, mumbai city, mh                   18
16, kolkata, howrah, wb                                 18
102, mumbai, mumbai city, mh                            17
Name: count, dtype: int64

In [100]:
patterns = {
    "street": r"\bst\b",
    "road": r"\brd\b",
    "avenue": r"\bave\b",
    "drive": r"\bdr\b",
    "boulevard": r"\bblvd\b",
    "highway": r"\bhwy\b",
    "lane": r"\bln\b",
    "apartment": r"\bapt\b",
}

for name, pattern in patterns.items():
    count = df["address_basic"].str.contains(
        pattern,
        regex=True,
        na=False
    ).sum()
    print(f"{name:12} : {count:,}")

street       : 331,436
road         : 326,238
avenue       : 224,220
drive        : 281,587
boulevard    : 25,903
highway      : 12,022
lane         : 116,402
apartment    : 35,543

In [101]:
print("ST examples:")
print(df.loc[
    df["address_basic"].str.contains(r"\bst\b", regex=True, na=False),
    "address_basic"
].sample(10).to_string(index=False))

print("\nRD examples:")
print(df.loc[
    df["address_basic"].str.contains(r"\brd\b", regex=True, na=False),
    "address_basic"
].sample(10).to_string(index=False))

ST examples:
            011447 24th st, phoenix, arizona
        181 wallens st, winsted, connecticut
435 mayview st, fayetteville, north carolina
    wisconsin rapids, #521 elm st, wisconsin
              houston, 2511 saltus st, texas
        413 minard st, jerseyville, illinois
              101-103 east st, bradner, ohio
     352 old stage st, adamsville, tennessee
    3885 cochrna st, simi valley, california
            8021. 26th st, phoennix, arizona

RD examples:
    87 pleasant hill rd, pink hill, north carolina
18639 whitlow ranch rd, pmb 9288, florence, ari...
               1540d terrace rd, roanoke, virginia
       001986 queens rd, rock hill, south carolina
           rock springs rd, wildesville, tennessee
            145 shipley rd, church hill, tennessee
                   2149. stine rd, peninsula, ohio
         308 shell rd, thomasville, north carolina
001280 coosie branch rd, lewisburg city, tennessee
fuquay-varina, 509- wake chapel rd, north carolina

In [102]:
df["address_basic"].value_counts().head(30)

address_basic
ground floor, bangalore, ka                             29
floor, mumbai, mh                                       26
18, kolkata, howrah, wb                                 26
303, mumbai, mh                                         25
12, ahmedabad, gj                                       23
101, mumbai, mumbai city, mh                            23
4, mumbai, mh                                           23
floor, bangalore, ka                                    22
7, kolkata, howrah, wb                                  21
5, ahmedabad, gj                                        21
601, mumbai, mh                                         21
301, mumbai, mumbai city, mh                            21
3, ahmedabad, gj                                        21
1, kolkata, howrah, wb                                  21
2, mumbai, mh                                           20
10, kolkata, howrah, wb                                 20
2, mumbai, mumbai city, mh                              20
3, kolkata, howrah, wb                                  20
4, kolkata, howrah, wb                                  20
2, kolkata, howrah, wb                                  20
301, mumbai, mh                                         19
1, mumbai, mh                                           19
1, chennai, tn                                          18
1948. weaver forest way, morrisville, north carolina    18
1, bangalore, ka                                        18
202, mumbai, mh                                         18
5, chennai, tn                                          18
ground floor, mumbai, mumbai city, mh                   18
16, kolkata, howrah, wb                                 18
102, mumbai, mumbai city, mh                            17
Name: count, dtype: int64

In [103]:
address_abbreviations = {
    r"\bst\b": "street",
    r"\brd\b": "road",
    r"\bave\b": "avenue",
    r"\bdr\b": "drive",
    r"\bblvd\b": "boulevard",
    r"\bhwy\b": "highway",
    r"\bln\b": "lane",
    r"\bapt\b": "apartment",
}

df["address_normalized"] = df["address_basic"]

for pattern, replacement in address_abbreviations.items():
    df["address_normalized"] = df["address_normalized"].str.replace(
        pattern,
        replacement,
        regex=True
    )

In [104]:
df[["address_basic", "address_normalized"]].sample(20)

,address_basic,address_normalized
3646428,"vishal tower, district center janakpuri, 212, ...","vishal tower, district center janakpuri, 212, ..."
1546013,"arizona, fllagstaff, <null>, 7550 rainbow ranc...","arizona, fllagstaff, <null>, 7550 rainbow ranc..."
3070940,"opposite nagar panchayat office, civil hospita...","opposite nagar panchayat office, civil hospita..."
2703905,"shree guru krupa ground floor, 1st main, heman...","shree guru krupa ground floor, 1st main, heman..."
3825754,"part of plot no. 3 swarn vihar. bhadana, rj, k...","part of plot no. 3 swarn vihar. bhadana, rj, k..."
46855,"110 mesquite street, mason, tx","110 mesquite street, mason, tx"
2281853,"1685 common dr, city of el paso, texas","1685 common drive, city of el paso, texas"
1184104,"flat no 10 moreshwar sco, mh, c/o vinod dhanra...","flat no 10 moreshwar sco, mh, c/o vinod dhanra..."
1836447,"6 chanteraine close, williamsburg city, virginia","6 chanteraine close, williamsburg city, virginia"
2084462,"building no. d-3/office no. 10, shree arihant ...","building no. d-3/office no. 10, shree arihant ..."
4508637,"door no 5/96 4a chettiar park road m m street,...","door no 5/96 4a chettiar park road m m street,..."
2786664,"13544 bentley cir, woodbridgge, virginia","13544 bentley cir, woodbridgge, virginia"
791852,"1888 cox rd, # e, asheboro, north carolina","1888 cox road, # e, asheboro, north carolina"
2134024,"425 basher drive, gadsden, alabama","425 basher drive, gadsden, alabama"
4493325,"#576 1/2 lakeway dr, pittsfield, massachusetts","#576 1/2 lakeway drive, pittsfield, massachusetts"
1895292,"no.33/18c/4, sankari road, srinivasa finance c...","no.33/18c/4, sankari road, srinivasa finance c..."
4174877,"49 bee mt road, oxford, connecticut","49 bee mt road, oxford, connecticut"
5042460,"no 78 vasudha enclave, pitampura, north west, dl","no 78 vasudha enclave, pitampura, north west, dl"
1705010,"door no 415 118, surat, gj","door no 415 118, surat, gj"
3394570,"626 third street, des moines, iowa","626 third street, des moines, iowa"

In [105]:
print("Basic normalized unique addresses:",
      df["address_basic"].nunique())

print("Abbreviation-normalized unique addresses:",
      df["address_normalized"].nunique())

print("Basic normalized duplicate rows:",
      len(df) - df["address_basic"].nunique())

print("Abbreviation-normalized duplicate rows:",
      len(df) - df["address_normalized"].nunique())

Basic normalized unique addresses: 4631187
Abbreviation-normalized unique addresses: 4468339
Basic normalized duplicate rows: 654416
Abbreviation-normalized duplicate rows: 817264

In [106]:
print("Missing addresses:", df["business_address"].isna().sum())
print("Missing address percentage:",
      df["business_address"].isna().mean() * 100)

Missing addresses: 175916
Missing address percentage: 3.3282106128666875

In [107]:
df["address_normalized"].value_counts().head(50)

address_normalized
ground floor, bangalore, ka                              29
floor, mumbai, mh                                        26
18, kolkata, howrah, wb                                  26
303, mumbai, mh                                          25
12, ahmedabad, gj                                        23
101, mumbai, mumbai city, mh                             23
4, mumbai, mh                                            23
floor, bangalore, ka                                     22
7, kolkata, howrah, wb                                   21
5, ahmedabad, gj                                         21
601, mumbai, mh                                          21
301, mumbai, mumbai city, mh                             21
3, ahmedabad, gj                                         21
1, kolkata, howrah, wb                                   21
2, mumbai, mh                                            20
10, kolkata, howrah, wb                                  20
2, mumbai, mumbai city, mh                               20
3, kolkata, howrah, wb                                   20
4, kolkata, howrah, wb                                   20
204-c central avenue, searcy, arkansas                   20
2, kolkata, howrah, wb                                   20
59-c water street, sandwich, massachusetts               19
127-131 reserve road, libby, montana                     19
301, mumbai, mh                                          19
508-c sorrells drive, jacksonville, arkansas             19
1, mumbai, mh                                            19
317 1/2 milwaukee street, houston, texas                 19
1, chennai, tn                                           18
1948. weaver forest way, morrisville, north carolina     18
10243 1/2 occidental avenue, seattle, washington         18
47 overlook road, waltham, massachusetts                 18
1, bangalore, ka                                         18
3416 kafka road, rio rancho, new mexico                  18
202, mumbai, mh                                          18
5, chennai, tn                                           18
ground floor, mumbai, mumbai city, mh                    18
16, kolkata, howrah, wb                                  18
8456 euclid avenue, chicago, illinois                    18
102, mumbai, mumbai city, mh                             17
10, mumbai, mumbai city, mh                              17
7992 victory garden lane, middletown, ohio               17
34 ewing avenue, southh bend, indiana                    17
13, mumbai, mh                                           17
3401 150, milan, indiana                                 17
no.1, chennai, tn                                        17
101, indore, mp                                          17
702, mumbai, mh                                          17
5, kolkata, howrah, wb                                   17
520 kathy lane, <null>, dayton, tennessee                17
124 walcott avenue, pmb 9350, staten island, new york    17
Name: count, dtype: int64

In [108]:
df[[
    "business_address",
    "address_basic",
    "address_normalized"
]].head(30)

,business_address,address_basic,address_normalized
0,"Mack Rd, Haltom City, Texas","mack rd, haltom city, texas","mack road, haltom city, texas"
1,NaN,NaN,NaN
2,"5780 Fawn Ct, Fort Worth, Texas","5780 fawn ct, fort worth, texas","5780 fawn ct, fort worth, texas"
3,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio","1 ivanhoe ave, po box 6009, cincinnati, ohio","1 ivanhoe avenue, po box 6009, cincinnati, ohio"
4,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...","door no 183, 41st cross, 22nd main 9th block j...","door no 183, 41st cross, 22nd main 9th block j..."
5,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...","2260- housecreek trail, unit 407, raleigh, nor...","2260- housecreek trail, unit 407, raleigh, nor..."
6,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...","6885 catalpa bluff ln, po box 5799, dickinson,...","6885 catalpa bluff lane, po box 5799, dickinso..."
7,"S03575 Cty Tk M, Town Of Buffalo, WI","s03575 cty tk m, town of buffalo, wi","s03575 cty tk m, town of buffalo, wi"
8,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri","##8 willow oak lane, fl. 0, saint louis, missouri","##8 willow oak lane, fl. 0, saint louis, missouri"
9,"343 Hempstead 161, Hope, Arkansas","343 hempstead 161, hope, arkansas","343 hempstead 161, hope, arkansas"
10,"46 White Rock Dr, Hurricanne, West Virginia","46 white rock dr, hurricanne, west virginia","46 white rock drive, hurricanne, west virginia"
11,"Raebareli, Rae Bareli, Raibareilly, UP, No #51...","raebareli, rae bareli, raibareilly, up, no #51...","raebareli, rae bareli, raibareilly, up, no #51..."
12,"189 Connmre Dr, Nashville, Tennessee","189 connmre dr, nashville, tennessee","189 connmre drive, nashville, tennessee"
13,"1113 Ash Street, Carlsbad, New Mexico","1113 ash street, carlsbad, new mexico","1113 ash street, carlsbad, new mexico"
14,"Saranampatti Roadvellakinar Post Coimbatore, T...","saranampatti roadvellakinar post coimbatore, t...","saranampatti roadvellakinar post coimbatore, t..."
15,"18900 Harl Weiller Road, Caldwell, Ohio","18900 harl weiller road, caldwell, ohio","18900 harl weiller road, caldwell, ohio"
16,"0200 Washington Street, ALVO, Nebraska","0200 washington street, alvo, nebraska","0200 washington street, alvo, nebraska"
17,"0315 Laramie St, Gillette, Wyoming","0315 laramie st, gillette, wyoming","0315 laramie street, gillette, wyoming"
18,"Rajendra Nagar, Andhra Pradesh, 221, 2Nd Floor...","rajendra nagar, andhra pradesh, 221, 2nd floor...","rajendra nagar, andhra pradesh, 221, 2nd floor..."
19,"15380 Fillmore Street, Unit 1006, Goodyear, Ar...","15380 fillmore street, unit 1006, goodyear, ar...","15380 fillmore street, unit 1006, goodyear, ar..."
20,"144 Foster Avenue, Harriman, Tennessee","144 foster avenue, harriman, tennessee","144 foster avenue, harriman, tennessee"
21,"Plot No.: 3829/3250, Near Metro Pillar No: 234...","plot no.: 3829/3250, near metro pillar no: 234...","plot no.: 3829/3250, near metro pillar no: 234..."
22,"Tiger Lily Lane, Madison, Indiana","tiger lily lane, madison, indiana","tiger lily lane, madison, indiana"
23,"#111 Frontage Road 2121, Ilfeld, New Mexico","#111 frontage road 2121, ilfeld, new mexico","#111 frontage road 2121, ilfeld, new mexico"
24,"Tennessee, 607 Fourth St, Columbia","tennessee, 607 fourth st, columbia","tennessee, 607 fourth street, columbia"
25,"Unit A3, Ugf, Plot No. 17, Satbari Vill., Chat...","unit a3, ugf, plot no. 17, satbari vill., chat...","unit a3, ugf, plot no. 17, satbari vill., chat..."
26,"Pt No 18, Nagpur, MH","pt no 18, nagpur, mh","pt no 18, nagpur, mh"
27,"1516 Marshall St, Iowa, PMB 2592, Boone","1516 marshall st, iowa, pmb 2592, boone","1516 marshall street, iowa, pmb 2592, boone"
28,"4-2, TN, Kanchipuram, Chinglepet","4-2, tn, kanchipuram, chinglepet","4-2, tn, kanchipuram, chinglepet"
29,"Shop No. 188, 1St Floor, Powai Plaza Cts No. 5...","shop no. 188, 1st floor, powai plaza cts no. 5...","shop no. 188, 1st floor, powai plaza cts no. 5..."

In [109]:
block_counts=(
    df.groupby(["country","name_core"])
    .size()
    .sort_values(ascending=False)
)
print(block_counts.head(30))

country  name_core
US       primary care           482
         physical therapy       477
         meridian               477
         pediatric dental       469
         urgent care            455
         womens health          438
         pediatric dentistry    429
         behavioral health      396
         internal medicine      395
         summit                 363
         pediatric              351
         cascade                341
         family center          332
         cedar                  318
         sterling               311
         vanguard               308
         earnosethroat.com      307
         cornerstone            299
         pinnacle               298
         lynx                   298
         apex                   296
         anchor                 294
         horizon                291
         helios                 290
         the dent               290
         straight edge          286
         foot & ankle           284
         aspen                  283
         granite                282
         beacon                 277
dtype: int64

In [110]:
block_counts = (
    df.groupby(["country", "name_core"])
      .size()
      .sort_values(ascending=False)
)

print("US:")
print(block_counts.loc["US"].head(20))

print("\nIndia:")
print(block_counts.loc["India"].head(20))

US:
name_core
primary care           482
physical therapy       477
meridian               477
pediatric dental       469
urgent care            455
womens health          438
pediatric dentistry    429
behavioral health      396
internal medicine      395
summit                 363
pediatric              351
cascade                341
family center          332
cedar                  318
sterling               311
vanguard               308
earnosethroat.com      307
cornerstone            299
pinnacle               298
lynx                   298
dtype: int64

India:
name_core
sc                    182
si                    174
ss                    155
st                    143
shree                 130
services              125
india                 123
se                    119
mumbai services       115
new delhi             114
ac                    106
solutions             102
sp                    100
sf                     96
international          93
sb                     90
new delhi services     87
global                 87
white                  84
sm                     83
dtype: int64

In [111]:
df.loc[
    (df["country"] == "India") &
    (df["name_core"].isin(["sc", "si", "ss", "st", "ac", "sp", "sf", "sb", "sm"])),
    ["business_name", "name_core", "country"]
].sample(30)

        business_name name_core country
405247             ST        st   India
2216638            SC        sc   India
2032256            SM        sm   India
5024912            SM        sm   India
1507790            SC        sc   India
305686             SP        sp   India
179272             ST        st   India
3499835            SC        sc   India
4785335            SP        sp   India
3971881            SP        sp   India
2525812            SI        si   India
3329478            SS        ss   India
4604409            SM        sm   India
4206642            SC        sc   India
744050             ST        st   India
455853             SF        sf   India
4313613            SI        si   India
5013427            SB        sb   India
4078326            SS        ss   India
4636466            SC        sc   India
4971553            AC        ac   India
2872440            SP        sp   India
3970550            ST        st   India
2184613            SI        si   India
1322689            SC        sc   India
601786             SC        sc   India
4205102            SC        sc   India
2932521            SF        sf   India
3632432            ST        st   India
3891838            SC        sc   India

In [112]:
missing = df.isna().sum()

missing_percent = (df.isna().mean() * 100).round(2)

missing_report = pd.DataFrame({
    "missing_count": missing,
    "missing_percent": missing_percent
})

print(missing_report)

                    missing_count  missing_percent
entity_id                       0             0.00
business_name                  13             0.00
business_address           175916             3.33
country                         0             0.00
name_basic                     13             0.00
name_unicode                   13             0.00
legal_form                3662372            69.29
name_core                      13             0.00
address_basic              175916             3.33
address_normalized         175916             3.33

In [113]:
df.loc[
    df["business_name"].isna(),
    ["entity_id", "business_name", "business_address", "country"]
]

,entity_id,business_name,business_address,country
160286,S3-391601813,NaN,"209 3rd Street, KY, Hardinsburg",US
1174547,S3-42389827,NaN,"137 - R, Industrial Area B, Near Pahwa Hospita...",India
1680112,S3-643806799,NaN,"Victoria Road, No.2, Karnataka, Bangalore",India
2486331,S3-754148834,NaN,"122 Hwy 173, Lake Arrowhead, CA",US
2544098,S3-825046378,NaN,"18520 Iola Street, Welda, KS",US
3093318,S3-834677797,NaN,"21-2, Vaibhav Mahim Chs, 220/222, Svs Road, Mu...",India
3112931,S3-749220699,NaN,"7517 Oleander Avenue, Chicago, IL",US
3155293,S3-263823274,NaN,"519 Odeneal Street, Dallas, TX",US
3349157,S3-640593334,NaN,"261/12 F/F Amritpuri B Garhi Jharia Maria, Sou...",India
3697228,S3-207014979,NaN,"C-2 Mansarovar Riico Industrial Area, Jaipur, ...",India
4638561,S3-382185873,NaN,"Kh No. 138, 1St Floor, Vill: Nawada, Vipin Gar...",India
4939588,S3-761073618,NaN,"H.No. 25/B East Anandpuri, Patna, Bihar",India
4973878,S3-617170111,NaN,"120 Shore Drive, Jarvisburg, North Carolina",US

In [114]:
print(df.dtypes)

entity_id                str
business_name            str
business_address         str
country                  str
name_basic               str
name_unicode             str
legal_form            object
name_core                str
address_basic            str
address_normalized       str
dtype: object

In [115]:
duplicate_rows = df.duplicated(
    subset=["business_name", "business_address", "country"]
)

print("Exact duplicate records:", duplicate_rows.sum())

Exact duplicate records: 18860

In [116]:
duplicates = df[
    df.duplicated(
        subset=["business_name", "business_address", "country"],
        keep=False
    )
]

print(
    duplicates[
        ["entity_id", "business_name", "business_address", "country"]
    ].sort_values("business_name").head(40)
)

            entity_id                    business_name  \
6699     S3-683879345                    # 3 AH Nasdaq
4152765  S3-216952998                    # 3 AH Nasdaq
5081440   S3-52513033                   # 7 OF Eqv LLC
1927912  S3-441978577                   # 7 OF Eqv LLC
69776    S3-196670208                    # 8 PU Stock,
4029602  S3-798865574                    # 8 PU Stock,
4304734  S3-284877451                       #2  Jersey
682129   S3-366851874                       #2  Jersey
4127909  S3-110447319                       #5 Finance
807784   S3-463997269                       #5 Finance
2961949  S3-216573854                         #5 Tech,
492740   S3-451894724                         #5 Tech,
1511404  S3-682904732                       #8 Stanley
2240616  S3-335706045                       #8 Stanley
2240211  S3-744388518                 #9 Yorkville LLC
2096352  S3-382581751                 #9 Yorkville LLC
1367494  S3-469981209                  #Baseex  Supply
2774037  S3-872702866                  #Baseex  Supply
3626124  S3-343164842                   #Patech  Vista
1752889    S3-8748634                   #Patech  Vista
1062133  S3-438777572                    #Vea  Bitwise
4980587  S3-345554019                    #Vea  Bitwise
2980198  S3-189604082                 #Zion Securities
5078077  S3-381820199                 #Zion Securities
2106281  S3-835510241                  #athenscultural
1227967  S3-226869704                  #athenscultural
1327653  S3-375596662                      #ecological
755860   S3-876862594                      #ecological
4970186  S3-222597840                       #evansqdro
4226250  S3-437620969                       #evansqdro
2076846  S3-492484465                #internalmedicine
1482272  S3-350829623                #internalmedicine
4755076  S3-841892488                        #mshotels
2708294  S3-268566262                        #mshotels
4340141  S3-551168623                    #rogersardisj
3729946  S3-202076721                    #rogersardisj
3709466  S3-571239621                    #swanphillips
2482719  S3-823310067                    #swanphillips
1613420  S3-962481304  (india) Mid Mundeshwari Private
1565076  S3-649138243  (india) Mid Mundeshwari Private

                                          business_address country
6699                      11686 35th Street, Yuma, Arizona      US
4152765                   11686 35th Street, Yuma, Arizona      US
5081440                                                NaN      US
1927912                                                NaN      US
69776           ##3027 Hickory Grove Ct, Fairfax, Virginia      US
4029602         ##3027 Hickory Grove Ct, Fairfax, Virginia      US
4304734       245 Goldbloom Lane, Sterling Ranch, Colorado      US
682129        245 Goldbloom Lane, Sterling Ranch, Colorado      US
4127909               4704 Clevesdale Dr, Cincinnati, Ohio      US
807784                4704 Clevesdale Dr, Cincinnati, Ohio      US
2961949              141 Grimm Way, Weirton, West Virginia      US
492740               141 Grimm Way, Weirton, West Virginia      US
1511404           201 Maple Street, Sugar Grove CITY, Ohio      US
2240616           201 Maple Street, Sugar Grove CITY, Ohio      US
2240211                 1432 Sandusky Ave, Tulsa, Oklahoma      US
2096352                 1432 Sandusky Ave, Tulsa, Oklahoma      US
1367494                     310 Sixth St, Wakeeney, Kansas      US
2774037                     310 Sixth St, Wakeeney, Kansas      US
3626124               4 Mason, Franklinton, North Carolina      US
1752889               4 Mason, Franklinton, North Carolina      US
1062133                 7401 Masters Dr, Potomac, Maryland      US
4980587                 7401 Masters Dr, Potomac, Maryland      US
2980198  001620 Gales St, Washington, District of Columbia      US
5078077  001620 Gales St, Washington, District of Columbia      US
2106281               116 County Rd 258, Athens, Tennessee      US
1227967               116 County Rd 258, Athens, Tennessee      US
1327653  Ps Srijan Corporate Park, Tower-ii, 3Rd Floor,...   India
755860   Ps Srijan Corporate Park, Tower-ii, 3Rd Floor,...   India
4970186                 17672 Mary Ann Dr, Lewes, Delaware      US
4226250                 17672 Mary Ann Dr, Lewes, Delaware      US
2076846          13892 Saddleback Dr, Moorpark, California      US
1482272          13892 Saddleback Dr, Moorpark, California      US
4755076  Siddharth Arcadeopp Holidaycamp Station Road, ...   India
2708294  Siddharth Arcadeopp Holidaycamp Station Road, ...   India
4340141               11642 Teal Ln, Marion County, Oregon      US
3729946               11642 Teal Ln, Marion County, Oregon      US
3709466            Missouri, Niangua, 31 Suncrest Dr Drive      US
2482719            Missouri, Niangua, 31 Suncrest Dr Drive      US
1613420  H.no 2Nd Floor, Universal Computer College Bui...   India
1565076  H.no 2Nd Floor, Universal Computer College Bui...   India

In [117]:
df["exact_duplicate"] = df.duplicated(
    subset=["business_name", "business_address", "country"],
    keep=False
)

print(df["exact_duplicate"].value_counts())

exact_duplicate
False    5248362
True       37241
Name: count, dtype: int64

In [118]:
id="r5x9k2"
exact_dups = df[df["exact_duplicate"]]

print("Exact duplicate rows:", len(exact_dups))

print(
    "\nDuplicate rows with missing address:",
    exact_dups["business_address"].isna().sum()
)

print(
    "Duplicate rows with non-missing address:",
    exact_dups["business_address"].notna().sum()
)

Exact duplicate rows: 37241

Duplicate rows with missing address: 438
Duplicate rows with non-missing address: 36803

In [119]:
print("Total entity IDs:", len(df))
print("Unique entity IDs:", df["entity_id"].nunique())
print("Duplicate entity IDs:", df["entity_id"].duplicated().sum())

Total entity IDs: 5285603
Unique entity IDs: 5285603
Duplicate entity IDs: 0

In [120]:
for col in ["business_name", "business_address", "country"]:
    empty = df[col].fillna("").str.strip().eq("").sum()
    print(f"{col}: {empty:,} empty/whitespace values")

business_name: 13 empty/whitespace values
business_address: 175,916 empty/whitespace values
country: 0 empty/whitespace values

In [121]:
df["name_length"] = df["name_core"].str.len()

print(df["name_length"].describe())

count    5.285590e+06
mean     2.289081e+01
std      9.202580e+00
min      0.000000e+00
25%      1.600000e+01
50%      2.200000e+01
75%      2.900000e+01
max      1.150000e+02
Name: name_length, dtype: float64

In [122]:
df["address_length"] = df["address_normalized"].str.len()

print(df["address_length"].describe())

count    5.109687e+06
mean     4.912950e+01
std      1.993811e+01
min      2.000000e+00
25%      3.700000e+01
50%      4.300000e+01
75%      5.600000e+01
max      2.400000e+02
Name: address_length, dtype: float64

In [123]:
print("Mean:", df["name_length"].mean())
print("Median:", df["name_length"].median())
print("Skewness:", df["name_length"].skew())

Mean:

 22.890814648884987
Median: 22.0
Skewness: 0.5445646786602645

In [124]:
print("Mean:", df["address_length"].mean())
print("Median:", df["address_length"].median())
print("Skewness:", df["address_length"].skew())

Mean: 49.12950499707712
Median: 43.0
Skewness: 1.5492550934003873

In [125]:
block_counts = (
    df.groupby(["country", "name_core"])
      .size()
)

print("Total blocks:", len(block_counts))

print("\nLargest blocks:")
print(block_counts.sort_values(ascending=False).head(20))

print("\nBlocks containing multiple records:",
      (block_counts > 1).sum())

Total blocks: 4204089

Largest blocks:
country  name_core
US       primary care           482
         physical therapy       477
         meridian               477
         pediatric dental       469
         urgent care            455
         womens health          438
         pediatric dentistry    429
         behavioral health      396
         internal medicine      395
         summit                 363
         pediatric              351
         cascade                341
         family center          332
         cedar                  318
         sterling               311
         vanguard               308
         earnosethroat.com      307
         cornerstone            299
         pinnacle               298
         lynx                   298
dtype: int64

Blocks containing multiple records: 413755

In [126]:
strong_blocks = (
    df.groupby(
        ["country", "name_core", "address_normalized"],
        dropna=False
    ).size()
)

print("Total blocks:", len(strong_blocks))

print("\nBlocks containing multiple records:",
      (strong_blocks > 1).sum())

print("\nLargest blocks:")
print(strong_blocks.sort_values(ascending=False).head(20))

Total blocks: 5203429

Blocks containing multiple records: 76463

Largest blocks:
country  name_core                             address_normalized
India    <city_name> companyprivate            709, hare krishna complex, pritamnagar ellisbrige, ahmedabad., ahmedabad, gj                                       5
US       flori's chemical                      #15410 cipres verde street, channelvieew, texas                                                                    5
India    east engineering                      NaN                                                                                                                5
US       redwood                               15 albany street, cazenovia, new york                                                                              5
         great committee                       1910 riviera boulevard, bullhead city township, arizona                                                            4
         amity's automotive                    4658 ketchikan avenue, salem, oregon                                                                               4
         chandra buchanan interstate pro       78 new bond street, worcester, massachusetts                                                                       4
         bright nasdaq                         3394 churchill lane, whitestown, indiana                                                                           4
         global diamond partnership            7641 palmgren avenue, otsego, minnesota                                                                            4
         gregory quartzsea                     ##50 harrington road, westminster, massachusetts                                                                   4
         ermengarde's cafe                     2445 wasco street, portland, oregon                                                                                4
         downtown barbershop                   3701 e19 fairbanks avenue, null, yakima, washington                                                                4
         family committee                      3005- 207, flaatwoods, kentucky                                                                                    4
         highland dynamix,                     175 2146, poteet, texas                                                                                            4
         charlotte human rights fresh project  6922 pear tree road, charlotte, north carolina                                                                     4
         archer archimedes                     1262 esperanza street, san bernardino, california                                                                  4
         health initiative                     219 william street, dwight, illinois                                                                               4
India    star software                         NaN                                                                                                                4
         ફોર્ચ્યુન એસ્ટેટ પ્રા. લિ.            arbuda bunglows, survey no.- 296, patidar soc, b/h paradise park, b/h old wadaj stand, old wadaj, ahmedabad, gj    4
US       corner barbershop                     NaN                                                                                                                4
dtype: int64

In [127]:
exact_blocks = strong_blocks[strong_blocks > 1]

print("Rows belonging to multi-record blocks:",
      exact_blocks.sum())

print("Number of multi-record blocks:",
      len(exact_blocks))

print("\nBlock size distribution:")
print(exact_blocks.value_counts().sort_index())

Rows belonging to multi-record blocks: 158637
Number of multi-record blocks: 76463

Block size distribution:
2    71053
3     5113
4      293
5        4
Name: count, dtype: int64

In [129]:
import sys

print(sys.executable)
print(sys.version)

c:\Users\madha\AppData\Local\Python\pythoncore-3.14-64\python.exe
3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)]