In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"D:\Amazon ML\dataset\student_resource\dataset\train\train_source3.tsv",sep="\t")

In [3]:
df.shape

(5285603, 4)

In [4]:
df.head

<bound method NDFrame.head of             entity_id                                business_name  \
0        S3-202863386                           wilfordhancock.com
1        S3-859268022  International South Consultants Private Ltd
2         S3-22467283                  LLC Moncada Léarning Center
3        S3-671162755                               Moyna's Coffee
4        S3-960981775                 Pvt. EFS Print Ventures Ltd.
...               ...                                          ...
5285598  S3-549653960                                Vip Solutions
5285599   S3-45212707                           Cornerstone Nippon
5285600  S3-257390113                              Legacy Piedmont
5285601   S3-97881155                         Pranava Meribl Trust
5285602  S3-864344230             The Trusted Defense Products Inc

                                          business_address country
0                              Mack Rd, Haltom City, Texas      US
1                                                      NaN   India
2                          5780 Fawn Ct, Fort Worth, Texas      US
3             1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4        Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India
...                                                    ...     ...
5285598                                                NaN   India
5285599               Paula Drive, Arkansas, N Little Rock      US
5285600                       Portland, Maine, Forest Park      US
5285601  235, 13Th Cross Road, Hoyasala Ngr 2D Stage, B...   India
5285602                                                NaN      US

[5285603 rows x 4 columns]>

In [5]:
df.info

<bound method DataFrame.info of             entity_id                                business_name  \
0        S3-202863386                           wilfordhancock.com
1        S3-859268022  International South Consultants Private Ltd
2         S3-22467283                  LLC Moncada Léarning Center
3        S3-671162755                               Moyna's Coffee
4        S3-960981775                 Pvt. EFS Print Ventures Ltd.
...               ...                                          ...
5285598  S3-549653960                                Vip Solutions
5285599   S3-45212707                           Cornerstone Nippon
5285600  S3-257390113                              Legacy Piedmont
5285601   S3-97881155                         Pranava Meribl Trust
5285602  S3-864344230             The Trusted Defense Products Inc

                                          business_address country
0                              Mack Rd, Haltom City, Texas      US
1                                                      NaN   India
2                          5780 Fawn Ct, Fort Worth, Texas      US
3             1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4        Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India
...                                                    ...     ...
5285598                                                NaN   India
5285599               Paula Drive, Arkansas, N Little Rock      US
5285600                       Portland, Maine, Forest Park      US
5285601  235, 13Th Cross Road, Hoyasala Ngr 2D Stage, B...   India
5285602                                                NaN      US

[5285603 rows x 4 columns]>

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB

In [7]:
df.isnull().sum()

entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

In [8]:
df.head

<bound method NDFrame.head of             entity_id                                business_name  \
0        S3-202863386                           wilfordhancock.com
1        S3-859268022  International South Consultants Private Ltd
2         S3-22467283                  LLC Moncada Léarning Center
3        S3-671162755                               Moyna's Coffee
4        S3-960981775                 Pvt. EFS Print Ventures Ltd.
...               ...                                          ...
5285598  S3-549653960                                Vip Solutions
5285599   S3-45212707                           Cornerstone Nippon
5285600  S3-257390113                              Legacy Piedmont
5285601   S3-97881155                         Pranava Meribl Trust
5285602  S3-864344230             The Trusted Defense Products Inc

                                          business_address country
0                              Mack Rd, Haltom City, Texas      US
1                                                      NaN   India
2                          5780 Fawn Ct, Fort Worth, Texas      US
3             1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio      US
4        Door No 183, 41St Cross, 22Nd Main 9Th Block J...   India
...                                                    ...     ...
5285598                                                NaN   India
5285599               Paula Drive, Arkansas, N Little Rock      US
5285600                       Portland, Maine, Forest Park      US
5285601  235, 13Th Cross Road, Hoyasala Ngr 2D Stage, B...   India
5285602                                                NaN      US

[5285603 rows x 4 columns]>

In [9]:
df.head(5)

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [10]:
df.head()

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

In [11]:
df.shape

(5285603, 4)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB

In [13]:
df.columns

Index(['entity_id', 'business_name', 'business_address', 'country'], dtype='str')

In [14]:
for col in df.select_dtypes(include="str").columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(20))

--- entity_id ---
entity_id
S3-202863386    1
S3-859268022    1
S3-22467283     1
S3-671162755    1
S3-960981775    1
S3-578159284    1
S3-121412624    1
S3-249416830    1
S3-107644605    1
S3-160217003    1
S3-504183980    1
S3-53737228     1
S3-16693061     1
S3-331103166    1
S3-45067784     1
S3-118652570    1
S3-90100170     1
S3-476778426    1
S3-128062172    1
S3-171901473    1
Name: count, dtype: int64

--- business_name ---
business_name
Primary Care           421
Physical Therapy       399
Pediatric Dental       393
Womens Health          379
Urgent Care            377
Pediatric Dentistry    361
Behavioral Health      330
Pediatric              321
Internal Medicine      319
The Dent               254
Straight Edge          252
Foot & Ankle           240
Ear Nose & Throat      238
earnosethroat.com      238
Main Street            231
Back Alley             222
SC                     197
Apex                   192
Vision                 185
SI                     180
Name: count, dtype: int64

--- business_address ---
business_address
NaN                             175916
Ground Floor, Bangalore, KA         29
Floor, Mumbai, MH                   26
18, Kolkata, Howrah, WB             26
303, Mumbai, MH                     25
12, Ahmedabad, GJ                   23
101, Mumbai, Mumbai City, MH        23
4, Mumbai, MH                       23
Floor, Bangalore, KA                22
7, Kolkata, Howrah, WB              21
5, Ahmedabad, GJ                    21
601, Mumbai, MH                     21
301, Mumbai, Mumbai City, MH        21
3, Ahmedabad, GJ                    21
1, Kolkata, Howrah, WB              21
2, Mumbai, MH                       20
10, Kolkata, Howrah, WB             20
2, Mumbai, Mumbai City, MH          20
3, Kolkata, Howrah, WB              20
4, Kolkata, Howrah, WB              20
Name: count, dtype: int64

--- country ---
country
US       3170056
India    2115547
Name: count, dtype: int64

In [15]:
df[df["business_name"].str.contains(
    r"\b(pvt|private|ltd|limited|corp|corporation)\b",
    case=False,
    na=False
)]["business_name"].value_counts().head(100)

C:\Users\madha\AppData\Local\Temp\ipykernel_13112\3185147793.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[df["business_name"].str.contains(

business_name
Mumbai Private Limited Center     51
Shree Private Limited Center      37
Life Private Limited Center       34
Hotel Private Limited Center      34
Gold Private Limited Center       33
                                  ..
One Private Limited Center        20
Arihant Private Limited Center    19
Laxmi Private Limited Center      19
Ss Private Limited Services       19
Bastion Corp                      19
Name: count, Length: 100, dtype: int64

In [16]:
matches = df[df["business_name"].str.contains(
    r"\b(?:pvt|private|ltd|limited|corp|corporation)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 1465088
business_name
Mumbai Private Limited Center     51
Shree Private Limited Center      37
Life Private Limited Center       34
Hotel Private Limited Center      34
Gold Private Limited Center       33
                                  ..
One Private Limited Center        20
Arihant Private Limited Center    19
Laxmi Private Limited Center      19
Ss Private Limited Services       19
Bastion Corp                      19
Name: count, Length: 100, dtype: int64

In [17]:
matches = df[df["business_name"].str.contains(
    r"\b(?:corp|corporation|)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 5285590
business_name
Primary Care         421
Physical Therapy     399
Pediatric Dental     393
Womens Health        379
Urgent Care          377
                    ...
Chiropractic Care    101
Southern             101
Prime                101
New Delhi            101
Aspen                100
Name: count, Length: 100, dtype: int64

In [18]:
matches=df[df["business_name"].str.contains(
    r"\bcorporation|corp\b",
    case=False,
    na=False
)]["business_name"].value_counts().head(100)

In [19]:
matches = df[df["business_name"].str.contains(
    r"\b(?:corp|corporation)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 198023
business_name
Meridian Corp                          21
Solstice Corp                          20
Bastion Corp                           19
Crestline Corp                         18
Lynx Corp                              17
                                       ..
Cardiology Care Associates Corp         9
Obsidian Corp                           9
Raven Corp                              9
Pediatric Dentistry Associates Corp     9
Summit Corporation                      9
Name: count, Length: 100, dtype: int64

In [20]:
matches = df[df["business_name"].str.contains(
    r"\b(?:pvt|private)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 860147
business_name
Mumbai Private Limited Center     51
Shree Private Limited Center      37
Life Private Limited Center       34
Hotel Private Limited Center      34
Gold Private Limited Center       33
                                  ..
My Private Limited Center         19
Shiva Private Limited Center      19
Sai Private Limited Services      19
Chennai Private Limited Center    19
Balaji Private Limited Center     19
Name: count, Length: 100, dtype: int64

In [21]:
matches = df[df["business_name"].str.contains(
    r"\b(?:ltd|limited)\b",
    case=False,
    na=False
)]

print("Matching rows:", len(matches))
print(matches["business_name"].value_counts().head(100))

Matching rows: 1101240
business_name
Mumbai Private Limited Center      51
Shree Private Limited Center       37
Life Private Limited Center        34
Hotel Private Limited Center       34
Gold Private Limited Center        33
                                   ..
Ss Private Limited Services        19
Creative Private Limited Center    19
Kolkata Pvt Ltd Center             19
My Private Limited Center          19
Shiva Private Limited Center       19
Name: count, Length: 100, dtype: int64

In [22]:
print("Missing:", df["business_address"].isna().sum())
print("Missing %:", df["business_address"].isna().mean() * 100)

Missing: 175916
Missing %: 3.3282106128666875

In [23]:
print("Empty:", df["business_address"].fillna("").str.strip().eq("").sum())

Empty: 175916

In [24]:
print("Unique addresses:", df["business_address"].nunique())
print("Duplicate rows:", df["business_address"].duplicated().sum())

Unique addresses: 4632764
Duplicate rows: 652838

In [25]:
print("Unique names:", df["business_name"].nunique())
print("Duplicate rows:", df["business_name"].duplicated().sum())

Unique names: 4651608
Duplicate rows: 633994

In [26]:
print(df["business_address"].value_counts(dropna=False).head(50))

business_address
NaN                                                     175916
Ground Floor, Bangalore, KA                                 29
Floor, Mumbai, MH                                           26
18, Kolkata, Howrah, WB                                     26
303, Mumbai, MH                                             25
12, Ahmedabad, GJ                                           23
101, Mumbai, Mumbai City, MH                                23
4, Mumbai, MH                                               23
Floor, Bangalore, KA                                        22
7, Kolkata, Howrah, WB                                      21
5, Ahmedabad, GJ                                            21
601, Mumbai, MH                                             21
301, Mumbai, Mumbai City, MH                                21
3, Ahmedabad, GJ                                            21
1, Kolkata, Howrah, WB                                      21
2, Mumbai, MH                                               20
10, Kolkata, Howrah, WB                                     20
2, Mumbai, Mumbai City, MH                                  20
3, Kolkata, Howrah, WB                                      20
4, Kolkata, Howrah, WB                                      20
2, Kolkata, Howrah, WB                                      20
301, Mumbai, MH                                             19
1, Mumbai, MH                                               19
1, Chennai, TN                                              18
1948. Weaver Forest Way, Morrisville, North Carolina        18
1, Bangalore, KA                                            18
202, Mumbai, MH                                             18
5, Chennai, TN                                              18
Ground Floor, Mumbai, Mumbai City, MH                       18
16, Kolkata, Howrah, WB                                     18
102, Mumbai, Mumbai City, MH                                17
10, Mumbai, Mumbai City, MH                                 17
13, Mumbai, MH                                              17
3401 150, Milan, Indiana                                    17
No.1, Chennai, TN                                           17
101, Indore, MP                                             17
702, Mumbai, MH                                             17
5, Kolkata, Howrah, WB                                      17
301, Ahmedabad, GJ                                          17
101, Mumbai, MH                                             17
6, Mumbai, MH                                               17
1108 1340, Orem, Utah                                       17
8, Kolkata, Howrah, WB                                      17
201, Mumbai, MH                                             17
501, Mumbai, Mumbai City, MH                                17
12, Kolkata, Howrah, WB                                     17
3, Mumbai, MH                                               16
401, Mumbai, Mumbai City, MH                                16
##24233 48, Woodland, Alabama                               16
4, Mumbai, Mumbai City, MH                                  16
Name: count, dtype: int64

In [27]:
for col in df.select_dtypes(include="str").columns:
    count = (
        df[col].notna() &
        (df[col] != df[col].str.strip())
    ).sum()

    print(col, "→", count)

entity_id → 0
business_name → 0
business_address → 0
country → 0

In [28]:
for col in df.select_dtypes(include="str").columns:
    original = df[col].dropna()
    normalized = original.str.strip().str.lower()

    print(
        col,
        "→ original unique:", original.nunique(),
        "| lowercase unique:", normalized.nunique()
    )

entity_id → original unique: 5285603 | lowercase unique: 5285603
business_name → original unique: 4651608 | lowercase unique: 4579083
business_address → original unique: 4632764 | lowercase unique: 4632184
country → original unique: 2 | lowercase unique: 2

In [29]:
name_norm = (
    df["business_name"]
    .astype("string")
    .str.strip()
    .str.lower()
)

groups = (
    pd.DataFrame({
        "original": df["business_name"],
        "normalized": name_norm
    })
    .dropna()
    .groupby("normalized")["original"]
    .nunique()
    .sort_values(ascending=False)
)

print(groups.head(30))

normalized
department of environmental protection    5
division of motor vehicles                5
division of housing                       5
ear nose & throat care associates llc     5
frontier institute of technology          5
department of education llc               5
foot & ankle physicians llc               5
eye clinic llc                            5
cardiology care llc                       5
department of finance                     5
commission on health                      5
commission on sanitation                  5
division of public works                  5
ear nose & throat associates llc          5
cardiology care associates llc            5
commission on veterans affairs            5
division of health                        5
eye partners llc                          5
ear nose & throat care llc                5
bureau of finance                         5
ear nose & throat physicians llc          5
department of housing                     5
ear nose & throat partners llc            5
foot & ankle partners llc                 5
foot & ankle clinic llc                   5
behavioral health care associates llc     5
bureau of public works                    5
bureau of transportation llc              5
division of parks and recreation          5
board of sanitation                       5
Name: original, dtype: int64

In [30]:
print(
    df.loc[
        name_norm == "department of environmental protection",
        "business_name"
    ].value_counts()
)

business_name
Department of Environmental Protection    3
DEPARTMENT OF ENVIRONMENTAL PROTECTION    1
Department Of Environmental Protection    1
Department OF Environmental Protection    1
department of environmental protection    1
Name: count, dtype: int64

In [31]:
name_norm = (
    df["business_name"]
    .astype("string")
    .str.strip()
    .str.lower()
)

mask = (
    df["business_name"].notna()
    & (df["business_name"] != name_norm)
)

print("Rows affected:", mask.sum())
print(df.loc[mask, ["business_name"]].drop_duplicates().head(100).to_string(index=False))

Rows affected: 4711315
                              business_name
International South Consultants Private Ltd
                LLC Moncada Léarning Center
                             Moyna's Coffee
               Pvt. EFS Print Ventures Ltd.
             LLC Hernandez Colonial Redwood
              Classic Equity Partners Group
             Ectolumdrex dba X+ Madison Inc
                    Animal Hanisch Hospirlg
                              Gomez Optimal
           The Rapid  Learning Alliance LLC
                 Indian Care Public Limited
                                      Béque
        அரிஹந்த் Foundation Private Limited
                        Wildlife Guild  LLC
                         Cinder Charlton-PC
                             ZRO Trinity Co
          Bajaj Foundation  Private Limited
                          Estell's Creative
                         Center 5uperior Co
                           Palace Vidyalaya
                             Global Applied
               Integrated  Business Systems
Cardiology Heartland Cáre Associates #98825
                  Sai  Surgical (India) Ltd
MW Management Private  Limited - 2067865001
                       FERRERO FERRERO DUKE
          Chinglepet Private Limited Center
                     Modern Center Brothers
                     Navkar Sons Ltd Center
                      Compher's Auto  Glass
                 గుజరాత్ Logistics లిమిటెడ్
             Stellar + Brothers Private Ltd
                 Ear N0se & Throat Regional
                 Best Software Innovations,
      Capital-Snow Capital-Snow Corporation
                               SAV Holdings
              Mr Om-Consultants Corporation
                             Cozy Shop Bike
                           LLC Safe Newbury
                Shree Sgpeciarity Pvt. Ltd.
                           Little Ice Cirhm
                                Hmgreen.Com
                              TV Tower Inc.
     Orthopedic Specialists Of Fort Wht LLC
                      Raj Black [Marketing]
                    M/s Jd Pvt Ltd Services
                         Davis  Acquisition
                           Mitchell Acbdeyg
                     Secure Secure Cárolina
                            Montica LLC Vii
                            Clear [Payroll]
                    Basalt Forefront L.L.C.
              Royal Mémorial Trust Holdings
                   Snell Cmpleee Glass Corp
  The Consultants Karnataka Cotex (Limited)
                       Honey Balzer, MD Ltd
                     Harbor Foundation  III
           Physical Group Precision Therapy
          Quonex d/b/a M D Herrera Offshore
         Ken Hospitalities (India)  Limited
                        Odetta Robinson Oak
   Bennett & Mofcno Canary of Liverpoo1 Ltd
          Private Shivam Projects [Limited]
        Chavarin Property óf Queensbury LLC
                             #Apexphotonics
        Perine Heritage Family Practice LLC
   Lopez Continental  Arcelormittal Greater
         Cultural Coalition Ltd Association
                   Jsg Enterprises (Center)
    Mr Chalakudy-+ Partners Private Limited
                       Leahy Silver  Acp LP
                            Edgar Space Inc
         Private Unique Enterprises Limited
                                  NV Pharma
         Karo1's Capital Restaurant  Clginc
         Umbraonyx dba Filson Apex Chemical
                Hyacinthe L. Cheung D.C. PC
                Piedmont Liberty Octave Llc
        Digital Hospitality Private Limited
                      Bonnettresilience.Com
  Solutions Accuracy Healthcare-Private Ltd
                     Tu Ventures  Pvt (Ltd)
                 Innovative Cargo  Concepts
             Heartland Optimal Médicine LLC
              Sachet Agro Infratech Limited
                                     Dental
                                 Monarch Co
           Mclaughlin, Blanco  & Walker Ltd
    Finance Divya Balaji  Private [Limited]
               (Ltd) Producer Aim Solutions
                   -- Maryl-Khalil Old Corp
                                    Wexnyla
                               Werner Aegon
       Insightful & Sons Industries Limited
           Baptist Ássociation Northside LP
    Morales, Godina & Pánkow Associates LLC
                     Germana Ott Slaect-Oyj
                           Lee Illumination
            Shaffer Xcblla LLC - 7934786696
                  Akridge Family [Practice]

In [32]:
print(df.shape)
print(df["business_name"].head(10))

(5285603, 4)
0                             wilfordhancock.com
1    International South Consultants Private Ltd
2                    LLC Moncada Léarning Center
3                                 Moyna's Coffee
4                   Pvt. EFS Print Ventures Ltd.
5                 LLC Hernandez Colonial Redwood
6                  Classic Equity Partners Group
7                 Ectolumdrex dba X+ Madison Inc
8                        Animal Hanisch Hospirlg
9                                  Gomez Optimal
Name: business_name, dtype: str

In [33]:
print(df.shape)
print(df.columns.tolist())
print(df.info())

(5285603, 4)
['entity_id', 'business_name', 'business_address', 'country']
<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB
None

In [34]:
print(df.isna().sum())

entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

In [35]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate entity IDs:", df["entity_id"].duplicated().sum())

Duplicate rows: 0
Duplicate entity IDs: 0

In [36]:
print(df["business_address"].dropna().sample(100, random_state=42).to_string(index=False))

                 781 Skyview Road, Salem, Virginia
Near Raunak Marriage Hall, Nalapar Afridiyan, R...
      123rd Ave, LKAE Stevens Township, Washington
447 Tranquila Drive, Camarillo Township, Califo...
              Morganton, 1254 Burkemont Avenue, NC
Keralam, Thirunakkra, Kottayam, Xii/74, First F...
Aligarh, #33 Panch Visa Jattari, Jatari, उत्तर ...
Gunjur, Door No 9245, Bangalore, KA, Gunjur Mai...
3490 Richpod-Rockfield Rd, Unit 6, Bowling Gree...
                   Sagecroft Drive, Houston, Texas
Hyderabad, Block-d, Maruthi Elite Gated Communi...
     2424 Heartstone Court, Clarksville, Tennessee
                230-234 3rd St, Ohio, Williamsburg
          Plot 300 244, Tilak Nagar, New Delhi, DL
708, Palms One, Royal Palms Estates Aarey Milk ...
46 Robert Ford Road, # 4, Watertown, Massachusetts
         916 Purple Moor Pass, Leanedr CITY, Texas
         16720 North Road, Martha Lake, Washington
           DL, Delhi, Wz-51a, First Floor Toda Pur
Hayatnagar, 3-53, Saroornagar, Sri Venkateswara...
                 508 8st St, Bucyrus, North Dakota
   #374 9-16-26, Vishakhapatnam, Visakhapatnam, AP
              Talwakars, Mahim, Mumbai, महाराष्ट्र
3031- Research Dr, PMB 5911, State College, Pen...
             380B Laneda Avenue, Manzanita, Oregon
12 Entire Basement And Ground Floor, New Delhi, DL
*Lien 1 Shop No 8 Tirupat, Complex Railway Road...
            Houston, Texas, #1614 Southmore Avenue
        1305 185th Dr, Goodyear, PMB 4324, Arizona
              5 West Street, <NULL>, Dellroy, Ohio
                                    B-12, Kota, RJ
2112-2114 Eighth St, Washington, District of Co...
                 434 Highland Court, Owensboro, KY
 126- Stewart Avenue, Moooresville, North Carolina
           #4515 Ghost Rider Way, Rimrock, Arizona
2580 Old A J Hwy, null, Strawberry Plains, Tenn...
Dheeraj Heritage, Comm Complex, Thane, Bg 26, M...
    Gateway Ln, N/A, Winston-Salem, North Carolina
               559  Ekman Drive, Batavia, Illinois
         Alaska, Fairbanks CITY, 452 Rhonda Street
            3405 25th Street, Tuscalooosa, Alabama
           B-60, Gautam Buddha Nagar, उत्तर प्रदेश
No. 3 Sfno 592/13, Avalurpettai Salai Kilpennat...
                Shop No.-##12, South Delhi, दिल्ली
           104 Mechunk Creek Drive, Troy, Virginia
              3- Maye St, Binghamton CDP, New York
              430 Devonshire Drive, Prosper, Texas
                         Lester Road, Medina, Ohio
                       No. 17, Madras, Chennai, TN
           1401 Ashland Ave, Saint Paul, Minnesota
    Eugene, 031547 Coburg Bottom Loop Road, Oregon
      #177 N Lacarpe Circle, Houma CITY, Louisiana
          2347 Blaine Drive, Chevy Chase, Maryland
   3034 Gardenia Lane, Floor 1, Oympia, Washington
      Mona Ln, Building 24, West Jordan City, Utah
No 2682 Nayabad, 1St Floor Fl-01, Kolkata, Howr...
             4304 Plantation Rd, Roanoke, Virginia
20, Opp. Balaji Furniture House Rajeev Colony, ...
   1250 Blue Hills Avenue, Bloomfield, Connecticut
              2944 1/2 8th St, Minot, North Dakota
                        A-00270, New Delhi, दिल्ली
Plot No.533, Dattasudha, Sindh Housing Society ...
                 1110 Chestnut St, Casper, Wyoming
1822 South Drive, Jacksonville CITY, North Caro...
157 Amcakassin Ter, Unit Apartment 2, Yonkers, ...
                  144 Lemcke Rd, Beavercreek, Ohio
                 07221 Heron Ln, Texas City, Texas
Flat No. A-7, New Shivsagar Housing Society, Ne...
#2050 (Old No. 29), 15Th Cross, Near Gundanjane...
5Thcross, 3Rdmain2Ndstage, Vijaynagar, KA, 2205...
           3380 Lakewood Dr, Harrionburg, Virginia
131, E-8, Basant Kunj, 12 No. Stop, Arera Colon...
             ##270 Munn Rd, Southbury, Connecticut
         7502 Monarch Mills Way, Coumbia, Maryland
              9236 158, Stokesdale, North Carolina
1114 Twenty-Ninth St, Winston-Salem, North Caro...
        Texas, Autsin CITY, 7600 Covered Bridge Dr
Thane, Vidarbha Mahesh Chs, C Bhavan Bldg, S N ...
21/1A/3, Darga Road, Jindal Towers Block-b, 5Th...
           ##7963 Throop Street, Chicago, Illinois
Gujranwala Town, DL, New Delhi, G-8 Kirpal Bhaw...
48 Scuppernong Lane, Southern Shores, North Car...
312 Millbrook Road, # 233, Raleigh, North Carolina
     158 6 B7near Main Bus Stand Kothrud, Pune, MH
    Apache Junction, Arizona, 1006 Santa Cruz Lane
800 Napa Valley Drive, Unit Apt 197, Little Roc...
            10866 69th Ave, Maple Grove, Minnesota
No 004, First Floor Sai Ram Paradise, Sujatha N...
                         A/2705, Thane, महाराष्ट्र
                 35-39 Russell Avenue, Niles, Ohio
                   NM, Carlsbad, 413 Laredo Street
            0108 Lakeside Drive, Smyrna, Tennessee
    118- Princeton Street, Manchester, Connecticut
               Cambridge Rd, Woburn, Massachusetts
   8661 Hotchkiss Street, Sterling Ranch, Colorado
                  Cleveland, Ohio, 573 124th Saint
           4041 Hillsdale Cir, Tuscaloosa, Alabama
          16 Meadows Avenue, Canton, Massachusetts
               30 Juno Drive, Wentzville, Missouri
Santi Niketan6 Race Course 6 Race Course, Coimb...

In [37]:
address_space = (
    df["business_address"].notna()
    & (df["business_address"] != df["business_address"].str.strip())
)

print("Addresses with leading/trailing spaces:", address_space.sum())

Addresses with leading/trailing spaces: 0

In [38]:
address_norm = (
    df["business_address"]
    .astype("string")
    .str.strip()
)

print(
    "Addresses affected by leading/trailing spaces:",
    (df["business_address"].notna() &
     (df["business_address"] != address_norm)).sum()
)

Addresses affected by leading/trailing spaces: 0

In [39]:
original_unique = df["business_address"].dropna().nunique()
normalized_unique = address_norm.dropna().nunique()

print("Original unique addresses:", original_unique)
print("After strip unique:", normalized_unique)

Original unique addresses: 4632764
After strip unique: 4632764

In [40]:
print(
    df["business_address"]
    .value_counts(dropna=False)
    .head(50)
)

business_address
NaN                                                     175916
Ground Floor, Bangalore, KA                                 29
Floor, Mumbai, MH                                           26
18, Kolkata, Howrah, WB                                     26
303, Mumbai, MH                                             25
12, Ahmedabad, GJ                                           23
101, Mumbai, Mumbai City, MH                                23
4, Mumbai, MH                                               23
Floor, Bangalore, KA                                        22
7, Kolkata, Howrah, WB                                      21
5, Ahmedabad, GJ                                            21
601, Mumbai, MH                                             21
301, Mumbai, Mumbai City, MH                                21
3, Ahmedabad, GJ                                            21
1, Kolkata, Howrah, WB                                      21
2, Mumbai, MH                                               20
10, Kolkata, Howrah, WB                                     20
2, Mumbai, Mumbai City, MH                                  20
3, Kolkata, Howrah, WB                                      20
4, Kolkata, Howrah, WB                                      20
2, Kolkata, Howrah, WB                                      20
301, Mumbai, MH                                             19
1, Mumbai, MH                                               19
1, Chennai, TN                                              18
1948. Weaver Forest Way, Morrisville, North Carolina        18
1, Bangalore, KA                                            18
202, Mumbai, MH                                             18
5, Chennai, TN                                              18
Ground Floor, Mumbai, Mumbai City, MH                       18
16, Kolkata, Howrah, WB                                     18
102, Mumbai, Mumbai City, MH                                17
10, Mumbai, Mumbai City, MH                                 17
13, Mumbai, MH                                              17
3401 150, Milan, Indiana                                    17
No.1, Chennai, TN                                           17
101, Indore, MP                                             17
702, Mumbai, MH                                             17
5, Kolkata, Howrah, WB                                      17
301, Ahmedabad, GJ                                          17
101, Mumbai, MH                                             17
6, Mumbai, MH                                               17
1108 1340, Orem, Utah                                       17
8, Kolkata, Howrah, WB                                      17
201, Mumbai, MH                                             17
501, Mumbai, Mumbai City, MH                                17
12, Kolkata, Howrah, WB                                     17
3, Mumbai, MH                                               16
401, Mumbai, Mumbai City, MH                                16
##24233 48, Woodland, Alabama                               16
4, Mumbai, Mumbai City, MH                                  16
Name: count, dtype: int64

In [41]:
empty_address = (
    df["business_address"]
    .astype("string")
    .str.strip()
    .eq("")
)

print("Empty addresses:", empty_address.sum())

Empty addresses: 0

In [42]:
print(
    df.loc[
        empty_address,
        "business_address"
    ].value_counts(dropna=False)
)

Series([], Name: count, dtype: int64)

In [43]:
for col in df.select_dtypes(include="str").columns:
    count = (
        df[col].notna() &
        (df[col] != df[col].str.strip())
    ).sum()

    print(f"{col}: {count}")

entity_id: 0
business_name: 0
business_address: 0
country: 0

In [44]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [45]:
address_length = df["business_address"].astype("string").str.len()

print("Mean:", address_length.mean())
print("Median:", address_length.median())
print("Skewness:", address_length.skew())

Mean: 48.32271918025507
Median: 42.0
Skewness: 1.560720077016944

In [46]:
Q1 = address_length.quantile(0.25)
Q3 = address_length.quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)

outliers = (address_length < lower) | (address_length > upper)

print("Outlier count:", outliers.sum())

Q1: 35
Q3: 55
IQR: 20
Lower bound: 5.0
Upper bound: 85.0
Outlier count: 355073

In [47]:
name_length = df["business_name"].astype("string").str.len()

print("Mean:", name_length.mean())
print("Median:", name_length.median())
print("Skewness:", name_length.skew())

Mean: 25.202200889588486
Median: 25.0
Skewness: 0.41363064040643693

In [48]:
Q1 = name_length.quantile(0.25)
Q3 = name_length.quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower)
print("Upper bound:", upper)

outliers = (name_length < lower) | (name_length > upper)

print("Outlier count:", outliers.sum())

Q1: 18
Q3: 31
IQR: 13
Lower bound: -1.5
Upper bound: 50.5
Outlier count: 50167

In [49]:
df["entity_id"].nunique()

5285603

In [50]:
print(df.shape)
print(df.info())
print(df.isna().sum())
print(df.nunique())

(5285603, 4)
<class 'pandas.DataFrame'>
RangeIndex: 5285603 entries, 0 to 5285602
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   entity_id         str
 1   business_name     str
 2   business_address  str
 3   country           str
dtypes: str(4)
memory usage: 161.3 MB
None
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64
entity_id           5285603
business_name       4651608
business_address    4632764
country                   2
dtype: int64

In [51]:
for col in df.columns:
    print(f"\n===== {col} =====")
    print("Unique:", df[col].nunique())
    print("Missing:", df[col].isna().sum())
    print(df[col].astype(str).str.len().describe())

===== entity_id =====
Unique: 5285603
Missing: 0
count    5.285603e+06
mean     1.188873e+01
std      3.512252e-01
min      5.000000e+00
25%      1.200000e+01
50%      1.200000e+01
75%      1.200000e+01
max      1.200000e+01
Name: entity_id, dtype: float64

===== business_name =====
Unique: 4651608
Missing: 13
count    5.285590e+06
mean     2.520220e+01
std      9.493565e+00
min      2.000000e+00
25%      1.800000e+01
50%      2.500000e+01
75%      3.100000e+01
max      1.230000e+02
Name: business_name, dtype: float64

===== business_address =====
Unique: 4632764
Missing: 175916
count    5.109687e+06
mean     4.832272e+01
std      2.017758e+01
min      2.000000e+00
25%      3.500000e+01
50%      4.200000e+01
75%      5.500000e+01
max      2.400000e+02
Name: business_address, dtype: float64

===== country =====
Unique: 2
Missing: 0
count    5.285603e+06
mean     3.200741e+00
std      1.469845e+00
min      2.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      5.000000e+00
max      5.000000e+00
Name: country, dtype: float64

In [52]:
print(df["country"].value_counts(dropna=False))

country
US       3170056
India    2115547
Name: count, dtype: int64

In [53]:
name_counts = df["business_name"].value_counts()

print(name_counts.head(30))

business_name
Primary Care           421
Physical Therapy       399
Pediatric Dental       393
Womens Health          379
Urgent Care            377
Pediatric Dentistry    361
Behavioral Health      330
Pediatric              321
Internal Medicine      319
The Dent               254
Straight Edge          252
Foot & Ankle           240
Ear Nose & Throat      238
earnosethroat.com      238
Main Street            231
Back Alley             222
SC                     197
Apex                   192
Vision                 185
SI                     180
Cascade                172
Global                 168
Human Rights           168
Division of            168
Summit                 166
Office of              163
Golden                 163
Commission on          162
Autism Assistance      161
SS                     160
Name: count, dtype: int64

In [54]:
patterns = r'private|pvt|limited|ltd|corporation|corp|inc|incorporated|llc|llp'

mask = df["business_name"].str.contains(
    patterns,
    case=False,
    na=False,
    regex=True
)

print(df.loc[mask, "business_name"].value_counts().head(50))

business_name
Meridian LLC                     83
Cedar LLC                        59
Slate LLC                        54
Sapphire LLC                     53
Atlas LLC                        53
Birch LLC                        52
Stag LLC                         52
Mumbai Private Limited Center    51
Ridgeline LLC                    50
Crestline LLC                    48
Zenith LLC                       48
Cornerstone LLC                  47
Compass LLC                      47
Meridian Inc                     47
Apex LLC                         47
Citadel LLC                      47
Beacon LLC                       46
Redwood LLC                      46
Amber LLC                        45
Kestrel LLC                      45
Titan LLC                        44
Everest LLC                      44
Aspen LLC                        44
Raven LLC                        43
Zephyr LLC                       43
Halcyon LLC                      43
Summit LLC                       42
Lyra LLC                         42
Sterling LLC                     42
Sequoia LLC                      42
Orion LLC                        42
Cardinal LLC                     42
Nova LLC                         42
Horizon LLC                      42
Anvil LLC                        41
Pinnacle LLC                     41
Cypress LLC                      41
Northwind LLC                    41
Lynx LLC                         41
Quartz LLC                       40
Cascade LLC                      40
Granite LLC                      40
Bastion LLC                      40
Jasper LLC                       40
Vertex LLC                       39
Monarch LLC                      39
Vanguard LLC                     39
Onyx LLC                         39
Willow LLC                       39
Basalt LLC                       38
Name: count, dtype: int64

In [55]:
for country in ["US", "India"]:
    print(f"\n===== {country} =====")
    
    temp = df[df["country"] == country]
    
    mask = temp["business_name"].str.contains(
        r'private|pvt|limited|ltd|corporation|corp|inc|incorporated|llc|llp',
        case=False,
        na=False,
        regex=True
    )
    
    print(temp.loc[mask, "business_name"].value_counts().head(20))

===== US =====
business_name
Meridian LLC       83
Cedar LLC          59
Slate LLC          54
Sapphire LLC       53
Atlas LLC          53
Birch LLC          52
Stag LLC           52
Ridgeline LLC      50
Crestline LLC      48
Zenith LLC         48
Cornerstone LLC    47
Compass LLC        47
Meridian Inc       47
Apex LLC           47
Citadel LLC        47
Beacon LLC         46
Redwood LLC        46
Amber LLC          45
Kestrel LLC        45
Titan LLC          44
Name: count, dtype: int64

===== India =====
business_name
Mumbai Private Limited Center       51
Shree Private Limited Center        37
Life Private Limited Center         34
Hotel Private Limited Center        34
Gold Private Limited Center         33
New Delhi Private Limited Center    32
Mumbai Private Limited Services     32
Jai Private Limited Center          32
Om Private Limited Center           32
Delhi Private Limited Center        32
Mumbai Pvt Ltd Center               30
Sai Private Limited Center          30
North Private Limited Center        30
New Private Limited Center          29
siprivate.com                       29
Digital Private Limited Services    28
Guru Private Limited Center         28
Dream Private Limited Center        28
Mumbai Limited Center               28
Perfect Private Limited Center      27
Name: count, dtype: int64

In [56]:
address_counts = df["business_address"].value_counts()

print(address_counts.head(30))

business_address
Ground Floor, Bangalore, KA                             29
Floor, Mumbai, MH                                       26
18, Kolkata, Howrah, WB                                 26
303, Mumbai, MH                                         25
12, Ahmedabad, GJ                                       23
101, Mumbai, Mumbai City, MH                            23
4, Mumbai, MH                                           23
Floor, Bangalore, KA                                    22
7, Kolkata, Howrah, WB                                  21
5, Ahmedabad, GJ                                        21
601, Mumbai, MH                                         21
301, Mumbai, Mumbai City, MH                            21
3, Ahmedabad, GJ                                        21
1, Kolkata, Howrah, WB                                  21
2, Mumbai, MH                                           20
10, Kolkata, Howrah, WB                                 20
2, Mumbai, Mumbai City, MH                              20
3, Kolkata, Howrah, WB                                  20
4, Kolkata, Howrah, WB                                  20
2, Kolkata, Howrah, WB                                  20
301, Mumbai, MH                                         19
1, Mumbai, MH                                           19
1, Chennai, TN                                          18
1948. Weaver Forest Way, Morrisville, North Carolina    18
1, Bangalore, KA                                        18
202, Mumbai, MH                                         18
5, Chennai, TN                                          18
Ground Floor, Mumbai, Mumbai City, MH                   18
16, Kolkata, Howrah, WB                                 18
102, Mumbai, Mumbai City, MH                            17
Name: count, dtype: int64

In [57]:
print(df["business_address"].dropna().sample(30, random_state=42).to_string(index=False))

                 781 Skyview Road, Salem, Virginia
Near Raunak Marriage Hall, Nalapar Afridiyan, R...
      123rd Ave, LKAE Stevens Township, Washington
447 Tranquila Drive, Camarillo Township, Califo...
              Morganton, 1254 Burkemont Avenue, NC
Keralam, Thirunakkra, Kottayam, Xii/74, First F...
Aligarh, #33 Panch Visa Jattari, Jatari, उत्तर ...
Gunjur, Door No 9245, Bangalore, KA, Gunjur Mai...
3490 Richpod-Rockfield Rd, Unit 6, Bowling Gree...
                   Sagecroft Drive, Houston, Texas
Hyderabad, Block-d, Maruthi Elite Gated Communi...
     2424 Heartstone Court, Clarksville, Tennessee
                230-234 3rd St, Ohio, Williamsburg
          Plot 300 244, Tilak Nagar, New Delhi, DL
708, Palms One, Royal Palms Estates Aarey Milk ...
46 Robert Ford Road, # 4, Watertown, Massachusetts
         916 Purple Moor Pass, Leanedr CITY, Texas
         16720 North Road, Martha Lake, Washington
           DL, Delhi, Wz-51a, First Floor Toda Pur
Hayatnagar, 3-53, Saroornagar, Sri Venkateswara...
                 508 8st St, Bucyrus, North Dakota
   #374 9-16-26, Vishakhapatnam, Visakhapatnam, AP
              Talwakars, Mahim, Mumbai, महाराष्ट्र
3031- Research Dr, PMB 5911, State College, Pen...
             380B Laneda Avenue, Manzanita, Oregon
12 Entire Basement And Ground Floor, New Delhi, DL
*Lien 1 Shop No 8 Tirupat, Complex Railway Road...
            Houston, Texas, #1614 Southmore Avenue
        1305 185th Dr, Goodyear, PMB 4324, Arizona
              5 West Street, <NULL>, Dellroy, Ohio

In [58]:
address_counts = df["business_address"].value_counts()

repeated_addresses = address_counts[
    address_counts >= 5
].head(20)

print(repeated_addresses)

business_address
Ground Floor, Bangalore, KA     29
Floor, Mumbai, MH               26
18, Kolkata, Howrah, WB         26
303, Mumbai, MH                 25
12, Ahmedabad, GJ               23
101, Mumbai, Mumbai City, MH    23
4, Mumbai, MH                   23
Floor, Bangalore, KA            22
7, Kolkata, Howrah, WB          21
5, Ahmedabad, GJ                21
601, Mumbai, MH                 21
301, Mumbai, Mumbai City, MH    21
3, Ahmedabad, GJ                21
1, Kolkata, Howrah, WB          21
2, Mumbai, MH                   20
10, Kolkata, Howrah, WB         20
2, Mumbai, Mumbai City, MH      20
3, Kolkata, Howrah, WB          20
4, Kolkata, Howrah, WB          20
2, Kolkata, Howrah, WB          20
Name: count, dtype: int64

In [59]:
df["name_basic"] = (
    df["business_name"]
    .str.lower()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

print(
    df[["business_name", "name_basic"]]
    .drop_duplicates()
    .head(30)
)

                                  business_name  \
0                            wilfordhancock.com
1   International South Consultants Private Ltd
2                   LLC Moncada Léarning Center
3                                Moyna's Coffee
4                  Pvt. EFS Print Ventures Ltd.
5                LLC Hernandez Colonial Redwood
6                 Classic Equity Partners Group
7                Ectolumdrex dba X+ Madison Inc
8                       Animal Hanisch Hospirlg
9                                 Gomez Optimal
10             The Rapid  Learning Alliance LLC
11                   Indian Care Public Limited
12                                        Béque
13                            #centraleducation
14          அரிஹந்த் Foundation Private Limited
15                          Wildlife Guild  LLC
16                           Cinder Charlton-PC
17                               ZRO Trinity Co
18            Bajaj Foundation  Private Limited
19                            Estell's Creative
20                           Center 5uperior Co
21                             Palace Vidyalaya
22                               Global Applied
23                 Integrated  Business Systems
24  Cardiology Heartland Cáre Associates #98825
25                    Sai  Surgical (India) Ltd
26  MW Management Private  Limited - 2067865001
27                         FERRERO FERRERO DUKE
28            Chinglepet Private Limited Center
29                       Modern Center Brothers

                                     name_basic
0                            wilfordhancock.com
1   international south consultants private ltd
2                   llc moncada léarning center
3                                moyna's coffee
4                  pvt. efs print ventures ltd.
5                llc hernandez colonial redwood
6                 classic equity partners group
7                ectolumdrex dba x+ madison inc
8                       animal hanisch hospirlg
9                                 gomez optimal
10              the rapid learning alliance llc
11                   indian care public limited
12                                        béque
13                            #centraleducation
14          அரிஹந்த் foundation private limited
15                           wildlife guild llc
16                           cinder charlton-pc
17                               zro trinity co
18             bajaj foundation private limited
19                            estell's creative
20                           center 5uperior co
21                             palace vidyalaya
22                               global applied
23                  integrated business systems
24  cardiology heartland cáre associates #98825
25                     sai surgical (india) ltd
26   mw management private limited - 2067865001
27                         ferrero ferrero duke
28            chinglepet private limited center
29                       modern center brothers

In [60]:
import unicodedata

def normalize_unicode(text):
    if pd.isna(text):
        return text
    
    return unicodedata.normalize("NFKC", text)

df["name_unicode"] = df["name_basic"].apply(normalize_unicode)

In [61]:
print(
    df[["business_name", "name_basic", "name_unicode"]]
    .drop_duplicates()
    .head(30)
)

                                  business_name  \
0                            wilfordhancock.com
1   International South Consultants Private Ltd
2                   LLC Moncada Léarning Center
3                                Moyna's Coffee
4                  Pvt. EFS Print Ventures Ltd.
5                LLC Hernandez Colonial Redwood
6                 Classic Equity Partners Group
7                Ectolumdrex dba X+ Madison Inc
8                       Animal Hanisch Hospirlg
9                                 Gomez Optimal
10             The Rapid  Learning Alliance LLC
11                   Indian Care Public Limited
12                                        Béque
13                            #centraleducation
14          அரிஹந்த் Foundation Private Limited
15                          Wildlife Guild  LLC
16                           Cinder Charlton-PC
17                               ZRO Trinity Co
18            Bajaj Foundation  Private Limited
19                            Estell's Creative
20                           Center 5uperior Co
21                             Palace Vidyalaya
22                               Global Applied
23                 Integrated  Business Systems
24  Cardiology Heartland Cáre Associates #98825
25                    Sai  Surgical (India) Ltd
26  MW Management Private  Limited - 2067865001
27                         FERRERO FERRERO DUKE
28            Chinglepet Private Limited Center
29                       Modern Center Brothers

                                     name_basic  \
0                            wilfordhancock.com
1   international south consultants private ltd
2                   llc moncada léarning center
3                                moyna's coffee
4                  pvt. efs print ventures ltd.
5                llc hernandez colonial redwood
6                 classic equity partners group
7                ectolumdrex dba x+ madison inc
8                       animal hanisch hospirlg
9                                 gomez optimal
10              the rapid learning alliance llc
11                   indian care public limited
12                                        béque
13                            #centraleducation
14          அரிஹந்த் foundation private limited
15                           wildlife guild llc
16                           cinder charlton-pc
17                               zro trinity co
18             bajaj foundation private limited
19                            estell's creative
20                           center 5uperior co
21                             palace vidyalaya
22                               global applied
23                  integrated business systems
24  cardiology heartland cáre associates #98825
25                     sai surgical (india) ltd
26   mw management private limited - 2067865001
27                         ferrero ferrero duke
28            chinglepet private limited center
29                       modern center brothers

                                   name_unicode
0                            wilfordhancock.com
1   international south consultants private ltd
2                   llc moncada léarning center
3                                moyna's coffee
4                  pvt. efs print ventures ltd.
5                llc hernandez colonial redwood
6                 classic equity partners group
7                ectolumdrex dba x+ madison inc
8                       animal hanisch hospirlg
9                                 gomez optimal
10              the rapid learning alliance llc
11                   indian care public limited
12                                        béque
13                            #centraleducation
14          அரிஹந்த் foundation private limited
15                           wildlife guild llc
16                           cinder charlton-pc
17                               zro trinity co
18             bajaj foundation private limited
19                            estell's creative
20                           center 5uperior co
21                             palace vidyalaya
22                               global applied
23                  integrated business systems
24  cardiology heartland cáre associates #98825
25                     sai surgical (india) ltd
26   mw management private limited - 2067865001
27                         ferrero ferrero duke
28            chinglepet private limited center
29                       modern center brothers

In [62]:
punctuation_mask = df["name_basic"].str.contains(
    r'[^\w\s]',
    regex=True,
    na=False
)

print("Names containing punctuation:",
      punctuation_mask.sum())

print("Percentage:",
      punctuation_mask.mean() * 100)

Names containing punctuation: 2119387
Percentage: 40.097355022690884

In [63]:
print(
    df.loc[
        punctuation_mask,
        "business_name"
    ].sample(30, random_state=42).to_string(index=False)
)

                आदित्य ऑल हॉस्पिटैलिटी प्रा. लि.
            Warren, Elliott and Love Ltd Service
                               Sai Sai [Academy]
                     Sanchez, Vikki, L.C.S.W. LP
                    ஜைன் அக்ரோ பிரைவேட் லிமிடெட்
                               A P & H Parts Llc
                ബാലാജി മീഡിയ പ്രൈവറ്റ് ലിമിറ്റഡ്
                        Newdelhitechnologies.Com
                               Helm Inc. Telecom
                                   Ironclad-Inc.
                          Om Construction L.L.P.
                            Masten & Sutton Inc.
                    Valerio's  Global Iron Works
             Chennai-Outsourcing Private Limited
        Noviyuma d/b/a Smith and Mejia Jaws Inc.
स्वस्तिक क्रिएटिव डेवलपर्स जनरल प्राइवेट लिमिटेड
                     Smt Mangal Global Pvt [Ltd]
                   Preferred-Media Partners Care
                       గుడ్ సాఫ్ట్‌వేర్ లిమిటెడ్
                                  Kesytnoe [Llc]
                      amf & sons private limited
                               Pvt. Air Eco Ltd.
         Priavnte Executive (India) Tech Limited
              स्मार्ट हेल्थकेयर प्राइवेट लिमिटेड
                                      fankle.com
                                   The Eye-Group
                   Evans's Metropolitan-Deli Inc
                           Becker, Mcginley  and
            Ariaquo Co f/k/a Capital Harvard LLC
                         Cardiology  Care L.L.C.

In [64]:
punctuation_mask = df["name_basic"].str.contains(
    r'[^\w\s]',
    regex=True,
    na=False
)

print("Names containing punctuation:",
      punctuation_mask.sum())

print("Percentage:",
      punctuation_mask.mean() * 100)

Names containing punctuation: 2119387
Percentage: 40.097355022690884

In [65]:
print(
    df.loc[
        punctuation_mask,
        "business_name"
    ].sample(30, random_state=42).to_string(index=False)
)

                आदित्य ऑल हॉस्पिटैलिटी प्रा. लि.
            Warren, Elliott and Love Ltd Service
                               Sai Sai [Academy]
                     Sanchez, Vikki, L.C.S.W. LP
                    ஜைன் அக்ரோ பிரைவேட் லிமிடெட்
                               A P & H Parts Llc
                ബാലാജി മീഡിയ പ്രൈവറ്റ് ലിമിറ്റഡ്
                        Newdelhitechnologies.Com
                               Helm Inc. Telecom
                                   Ironclad-Inc.
                          Om Construction L.L.P.
                            Masten & Sutton Inc.
                    Valerio's  Global Iron Works
             Chennai-Outsourcing Private Limited
        Noviyuma d/b/a Smith and Mejia Jaws Inc.
स्वस्तिक क्रिएटिव डेवलपर्स जनरल प्राइवेट लिमिटेड
                     Smt Mangal Global Pvt [Ltd]
                   Preferred-Media Partners Care
                       గుడ్ సాఫ్ట్‌వేర్ లిమిటెడ్
                                  Kesytnoe [Llc]
                      amf & sons private limited
                               Pvt. Air Eco Ltd.
         Priavnte Executive (India) Tech Limited
              स्मार्ट हेल्थकेयर प्राइवेट लिमिटेड
                                      fankle.com
                                   The Eye-Group
                   Evans's Metropolitan-Deli Inc
                           Becker, Mcginley  and
            Ariaquo Co f/k/a Capital Harvard LLC
                         Cardiology  Care L.L.C.

In [66]:
punctuation_mask = df["name_basic"].str.contains(
    r'[^\w\s]',
    regex=True,
    na=False
)

print("Names containing punctuation:", punctuation_mask.sum())
print("Percentage:", punctuation_mask.mean() * 100)

Names containing punctuation: 2119387
Percentage: 40.097355022690884